schedule: "every week on monday"
search: False
update: insecure
requirements:
  - requirements/default.txt:
      update: security
  - requirements/dev.txt:
      update: security
  - docs/requirements.txt:
      update: security
