schedule: "every week on monday"
search: False
update: insecure
requirements:
  - requirements.txt:
      update: security
  - requirements-dev.txt:
      update: security
  - docs/requirements.txt:
      update: security
