# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.27+.
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: server
    image: local/pontoon
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./documentation:/app/documentation
      - ./pontoon:/app/pontoon
      - ./requirements:/app/requirements
      - ./translate:/app/translate
      - ~/.ssh:/home/pontoon/.ssh

  # Database
  postgres:
    image: postgres:15
    environment:
      # Create the superuser account
      - POSTGRES_USER=pontoon
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=pontoon
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

# Persist database
volumes:
  pgdata: null
