[pytest]
addopts = --reuse-db
norecursedirs = .git _build commands media node_modules requirements tmp*
DJANGO_SETTINGS_MODULE = pontoon.settings
filterwarnings =
    ignore::DeprecationWarning:notifications
    ignore::DeprecationWarning:distutils
    ignore::django.utils.deprecation.RemovedInDjango51Warning:notifications

