line-length = 88
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
ignore = [
    "E501",  # Line too long
]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "W",  # pycodestyle warnings
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

docstring-code-format = false
docstring-code-line-length = "dynamic"
