<div id="intro">

	<h2><?php echo _w('Privacy Policy')?></h2>

	<h3><?php echo _w('Mozilla Test Pilot')?></h3>
	<p><?php echo _w('Adopted: August 11, 2009')?></p>
	<p><?php echo _w('Revised: April 28, 2010')?></p>
	<p><?php echo _w('We’re working hard to protect your privacy while delivering products and services that bring you the performance and protection you desire in your personal computing.  This Mozilla Test Pilot Privacy Policy (“Policy”) explains how Mozilla Corporation (“Mozilla”), a wholly-owned subsidiary of the non-profit Mozilla Foundation, collects and uses information from user tests conducted through Mozilla’s Test Pilot program (“Test Pilot”).  It does not apply to other Mozilla websites, products or services, each of which have their own privacy policy.  If you are using another Mozilla product at the time you are participating in Test Pilot, you should look at the relevant privacy policy to determine what other information is being collected (e.g., See Mozilla’s <a href="http://www.mozilla.com/en-US/legal/privacy/firefox-en.html">Firefox Privacy Policy</a> for further information on data collected from all Firefox users).')?></p>
  
    <h3><?php echo _w('What is Test Pilot?')?></h3>
	<p><?php echo _w('Test Pilot was created to provide a new set of tools and capabilities to increase the efficiency and effectiveness of our user testing.  Test Pilot is a stand-alone platform.  Test Pilot may be used as an add-on to your web browser, or bundled into other products.  However Test Pilot is made available, you will always have to choose to submit your data and unless you do so, no data will be transfered to Test Pilot server.  You are in control. You choose to participate and you choose to share your data. No data will be collected unless you choose to do so. Please visit <a href="https://labs.mozilla.com/projects/test-pilot/">https://labs.mozilla.com/projects/test-pilot/</a> for more information on Test Pilot.')?></p>

    <h3><?php echo _w('Information Collected from Test Pilot Participants')?></h3>
	<p><?php echo _w('In order to improve our user testing, Mozilla will collect certain data in relation to your participation in Test Pilot tests. Your data won\'t be transmitted until you choose to submit your data.&nbsp; When your data is submitted, it will be aggregated into a big batch with everyone else\'s info and will not be directly connected back to you. All the aggregated data will be open to the public, but to be extra clear none of it will be personally identifiable as yours or anyone else\'s.')?></p>
	<p><?php echo _w('After you install Test Pilot, you will have an opportunity to review a description of each test, including its duration and the types of data that will be collected through the test (the “Test Description”). The data required for the test (“Test Data”) will be collected locally on your computer in a database within Firefox. At the end of the test, you will be able to review the Test Data and will be asked whether you would like to submit the Test Data to Mozilla. ')?></p>
	<p><?php echo _w('The Test Data consist of information that cannot be directly associated with a specific person or entity, and include your self-assessed technical level, computer configuration, the version of Firefox or other products that you use, the URL or Uniform Resource Locators (the addresses of web pages you navigate). The Test Data do not include your name or email address, and will not be combined with any information that personally identifies you.')?></p>
	<p><?php echo _w('If you change your mind about participating in a test, you may opt out from the test at any time before you choose to share the Test Data, and the Test Data will not be transmitted to Mozilla. Similarly, if you choose not to submit the Test Data at the end of the test, the Test Data will not be transmitted to Mozilla.')?></p>

</div>
