import React from 'react';
import { Localized } from '@fluent/react';

/**
 * Show the translation source for a suggestion generated by OpenAI ChatGPT.
 */
export function OpenAITranslation(): React.ReactElement<'li'> {
  return (
    <li>
      <Localized id='machinery-OpenAITranslation--translation-source'>
        <span className='translation-source'>OPENAI CHATGPT</span>
      </Localized>
    </li>
  );
}
