# Generated by Django 4.2.22 on 2025-07-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_personalaccesstoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalaccesstoken",
            name="token_id",
            field=models.CharField(default=123, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
