# Generated by Django 4.2.22 on 2025-07-14 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_personalaccesstoken_token_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalaccesstoken",
            name="token_id",
        ),
    ]
