# Generated by Django 4.2.22 on 2025-07-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_personalaccesstoken_token_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalaccesstoken",
            old_name="note",
            new_name="description",
        ),
        migrations.AddField(
            model_name="personalaccesstoken",
            name="name",
            field=models.CharField(default="hello", max_length=128),
            preserve_default=False,
        ),
    ]
