# Generated by Django 4.2.22 on 2025-07-29 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_note_personalaccesstoken_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalaccesstoken",
            name="description",
        ),
    ]
