# Generated by Django 4.2.22 on 2025-08-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_personalaccesstoken_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalaccesstoken",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
