# Generated by Django 4.2.11 on 2024-09-18 19:47

import django.db.models.deletion
import django.utils.timezone

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0065_fix_projectlocale_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notification", models.BooleanField(default=False)),
                ("email", models.BooleanField(default=False)),
                ("transactional", models.BooleanField(default=False)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("managers", models.BooleanField(default=True)),
                ("translators", models.BooleanField(default=True)),
                ("contributors", models.BooleanField(default=True)),
                (
                    "translation_minimum",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "translation_maximum",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("translation_from", models.DateField(blank=True, null=True)),
                ("translation_to", models.DateField(blank=True, null=True)),
                ("review_minimum", models.PositiveIntegerField(blank=True, null=True)),
                ("review_maximum", models.PositiveIntegerField(blank=True, null=True)),
                ("review_from", models.DateField(blank=True, null=True)),
                ("review_to", models.DateField(blank=True, null=True)),
                ("login_from", models.DateField(blank=True, null=True)),
                ("login_to", models.DateField(blank=True, null=True)),
                (
                    "locales",
                    models.ManyToManyField(related_name="messages", to="base.locale"),
                ),
                (
                    "projects",
                    models.ManyToManyField(related_name="messages", to="base.project"),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="received_messages", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("notification", True), ("email", True), _connector="OR"
                ),
                name="at_least_one_message_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("managers", True),
                    ("translators", True),
                    ("contributors", True),
                    _connector="OR",
                ),
                name="at_least_one_user_role",
            ),
        ),
    ]
