# Generated by Django 4.2.17 on 2024-12-12 13:37

from pathlib import Path

from django.db import migrations


def populate_email_content(apps, schema_editor):
    EmailContent = apps.get_model("messaging", "EmailContent")

    module_dir = Path(__file__).parent.parent
    email_directory = module_dir / "templates/messaging/emails/content"

    SUBJECTS = {
        "onboarding_1": "Welcome to Pontoon!",
        "onboarding_2": "Translating on Pontoon",
        "onboarding_3": "More resources for contributors",
        "inactive_contributor": "Mozilla Pontoon account status",
        "inactive_translator": "Reminder: Contributing to Mozilla Pontoon as a Translator",
        "inactive_manager": "Reminder: Contributing to Mozilla Pontoon as a Team Manager",
    }

    for name, subject in SUBJECTS.items():
        file_path = email_directory / f"{name}.html"
        body = file_path.read_text()

        EmailContent.objects.create(email=name, body=body, subject=subject)


def remove_email_content(apps, schema_editor):
    EmailContent = apps.get_model("messaging", "EmailContent")
    EmailContent.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_emailcontent"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_email_content,
            reverse_code=remove_email_content,
        ),
    ]
