# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("actionlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("translation:created", "Translation created"),
                    ("translation:deleted", "Translation deleted"),
                    ("translation:approved", "Translation approved"),
                    ("translation:unapproved", "Translation unapproved"),
                    ("translation:rejected", "Translation rejected"),
                    ("translation:unrejected", "Translation unrejected"),
                    ("comment:added", "Comment added"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="performed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
