# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actionlog", "0002_auto_20200123_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("translation:created", "Translation created"),
                    ("translation:deleted", "Translation deleted"),
                    ("translation:approved", "Translation approved"),
                    ("translation:unapproved", "Translation unapproved"),
                    ("translation:rejected", "Translation rejected"),
                    ("translation:unrejected", "Translation unrejected"),
                    ("translation_comment:added", "Comment added"),
                    ("team_comment:added", "Comment added"),
                ],
                max_length=50,
            ),
        ),
    ]
