# Generated by Django 2.2.13 on 2020-07-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0002_auto_20200703_0709'),
        ('actionlog', '0002_auto_20200702_1656'),
    ]

    operations = [
    ]
