# Generated by Django 4.2.16 on 2024-11-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0067_remove_userprofile_community_builder_level_and_more"),
        ("actionlog", "0005_migrate_old_translations_to_actionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="tm_entries",
            field=models.ManyToManyField(blank=True, to="base.translationmemoryentry"),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("translation:created", "Translation created"),
                    ("translation:deleted", "Translation deleted"),
                    ("translation:approved", "Translation approved"),
                    ("translation:unapproved", "Translation unapproved"),
                    ("translation:rejected", "Translation rejected"),
                    ("translation:unrejected", "Translation unrejected"),
                    ("comment:added", "Comment added"),
                    ("tm_entry:deleted", "TranslationMemoryEntry deleted"),
                    ("tm_entries:edited", "TranslationMemoryEntries edited"),
                    ("tm_entries:uploaded", "TranslationMemoryEntries uploaded"),
                ],
                max_length=50,
            ),
        ),
    ]
