# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 13:00
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_squashed_0154_auto_20200206_1736"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                        ],
                        max_length=50,
                    ),
                ),
                ("definition", models.TextField(blank=True)),
                ("usage", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Approved"),
                            ("new", "New"),
                            ("obsolete", "Obsolete"),
                            ("review", "Review"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("case_sensitive", models.BooleanField(default=False)),
                ("exact_match", models.BooleanField(default=False)),
                ("do_not_translate", models.BooleanField(default=False)),
                ("forbidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="base.Locale",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="terminology.Term",
                    ),
                ),
            ],
        ),
    ]
