# Generated by Django 2.2.11 on 2020-05-07 16:50

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.Entity",
            ),
        ),
    ]
