# Generated by Django 2.2.13 on 2020-07-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("terminology", "0002_term_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
