# Generated by Django 3.2.14 on 2022-09-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terminology", "0003_auto_20200703_0710"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="term",
            name="exact_match",
        ),
    ]
