# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-12 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0121_bug_1453999_disable_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(choices=[(b'pontoon', b'pontoon'), (b'translate-toolkit', b'translate-toolkit'), (b'compare-locales', b'compare-locales')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='base.Translation')),
            ],
            options={
                'ordering': ('library', 'message'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(choices=[(b'pontoon', b'pontoon'), (b'translate-toolkit', b'translate-toolkit'), (b'compare-locales', b'compare-locales')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='base.Translation')),
            ],
            options={
                'ordering': ('library', 'message'),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='warning',
            unique_together=set([('translation', 'library', 'message')]),
        ),
        migrations.AlterUniqueTogether(
            name='error',
            unique_together=set([('translation', 'library', 'message')]),
        ),
    ]
