# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-16 19:33
from __future__ import unicode_literals

from django.db import migrations


def remove_warnings_and_errors(apps, schema_editor):
    """
    Remove all warnings and errors related to Translate Toolkit.
    """
    Warning = apps.get_model('checks', 'Warning')
    Error = apps.get_model('checks', 'Error')

    Warning.objects.filter(
        library='tt'
    ).delete()
    Error.objects.filter(
        library='tt'
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            remove_warnings_and_errors,
            migrations.RunPython.noop,
        )
    ]
