# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_remove_translate_toolkit_errors_and_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='library',
            field=models.CharField(choices=[(b'p', b'pontoon'), (b'cl', b'compare-locales')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='warning',
            name='library',
            field=models.CharField(choices=[(b'p', b'pontoon'), (b'cl', b'compare-locales')], db_index=True, max_length=20),
        ),
    ]
