# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models

"""
This migration was triggered by black formatting. It doesn't actually change anything
to our models, only text that was formatted differently. Please ignore this as it is
merely cosmetic (and the easiest way to get rid of those false migrations).
"""


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0003_auto_20180716_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="error",
            name="library",
            field=models.CharField(
                choices=[("p", "pontoon"), ("cl", "compare-locales")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="warning",
            name="library",
            field=models.CharField(
                choices=[("p", "pontoon"), ("cl", "compare-locales")],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
