# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 16:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0108_reverse_accessors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('priority', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Project')),
                ('resources', models.ManyToManyField(to='base.Resource')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('slug', 'project')]),
        ),
    ]
