# Generated by Django 4.2.22 on 2025-06-11 14:55

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0081_fix_android_spaces"),
        ("tags", "0001_squashed_0002_set_tag_priority_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="base.project",
            ),
        ),
    ]
