# Generated by Django 1.11.28 on 2020-03-08 19:30
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0002_auto_20200322_1821"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.Project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepositorySyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "project_sync_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository_sync_logs",
                        to="sync.ProjectSyncLog",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.Repository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="projectsynclog",
            name="sync_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_sync_logs",
                to="sync.SyncLog",
            ),
        ),
        migrations.AddField(
            model_name="projectsynclog",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectsynclog",
            name="skipped_end_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
