# Generated by Django 1.11.28 on 2020-03-08 19:30
from django.db import migrations


SYNC_USER = {
    "username": "pontoon-sync",
    "email": "pontoon-sync@mozilla.com",
    "first_name": "Sync",
}


def add_sync_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("base", "UserProfile")

    user = User(**SYNC_USER)
    user.save()

    profile = UserProfile(user=user)
    profile.save()


def remove_sync_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("base", "UserProfile")

    user = User.objects.find(username=SYNC_USER["username"])
    user_profile = UserProfile.objects.find(user=user)

    user_profile.delete()
    user.delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sync", "0001_squashed_0004_add-sync-system-user"),
    ]

    operations = [
        migrations.RunPython(code=add_sync_user, reverse_code=remove_sync_user,),
    ]
