# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-08 19:30
from django.db import migrations


def update_sync_user_email(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(email="pontoon-sync@mozilla.org").update(
        email="pontoon-sync@mozilla.com"
    )


def revert_sync_user_email(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(email="pontoon-sync@mozilla.com").update(
        email="pontoon-sync@mozilla.org"
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sync", "0001_squashed_0004_add-sync-system-user"),
    ]

    operations = [
        migrations.RunPython(
            code=update_sync_user_email, reverse_code=revert_sync_user_email,
        ),
    ]
