# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 15:58
from __future__ import unicode_literals

from django.db import migrations


SYNC_USER = {
    "username": "pontoon-sync",
    "email": "pontoon-sync@mozilla.org",
    "first_name": "Sync",
}


def add_sync_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("base", "UserProfile")

    user = User(**SYNC_USER)
    user.save()

    profile = UserProfile(user=user)
    profile.save()


def remove_sync_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("base", "UserProfile")

    user = User.objects.find(username=SYNC_USER["username"])
    user_profile = UserProfile.objects.find(user=user)

    user_profile.delete()
    user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_auto_20151204_2343"),
    ]

    operations = [
        migrations.RunPython(add_sync_user, remove_sync_user,),
    ]
