# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20151204_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('error_message', models.TextField(blank=True)),
                ('repository_sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_files', to='sync.RepositorySyncLog')),
            ],
        ),
    ]
