# Generated by Django 4.2.17 on 2025-01-16 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0004_migrate_sync_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repositorysynclog",
            name="project_sync_log",
        ),
        migrations.RemoveField(
            model_name="repositorysynclog",
            name="repository",
        ),
        migrations.DeleteModel(
            name="ProjectSyncLog",
        ),
        migrations.DeleteModel(
            name="RepositorySyncLog",
        ),
        migrations.DeleteModel(
            name="SyncLog",
        ),
    ]
