# Generated by Django 3.1.3 on 2020-12-10 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pontoon.insights.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0012_auto_20201020_1830"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocaleInsightsSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_strings", models.PositiveIntegerField(default=0)),
                ("approved_strings", models.PositiveIntegerField(default=0)),
                ("fuzzy_strings", models.PositiveIntegerField(default=0)),
                ("strings_with_errors", models.PositiveIntegerField(default=0)),
                ("strings_with_warnings", models.PositiveIntegerField(default=0)),
                ("unreviewed_strings", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("total_managers", models.PositiveIntegerField(default=0)),
                ("total_reviewers", models.PositiveIntegerField(default=0)),
                ("total_contributors", models.PositiveIntegerField(default=0)),
                (
                    "active_users_last_12_months",
                    models.JSONField(
                        default=pontoon.insights.models.active_users_default
                    ),
                ),
                (
                    "active_users_last_6_months",
                    models.JSONField(
                        default=pontoon.insights.models.active_users_default
                    ),
                ),
                (
                    "active_users_last_3_months",
                    models.JSONField(
                        default=pontoon.insights.models.active_users_default
                    ),
                ),
                (
                    "active_users_last_month",
                    models.JSONField(
                        default=pontoon.insights.models.active_users_default
                    ),
                ),
                ("unreviewed_suggestions_lifespan", models.DurationField()),
                ("completion", models.FloatField()),
                ("human_translations", models.PositiveIntegerField(default=0)),
                ("machinery_translations", models.PositiveIntegerField(default=0)),
                ("new_source_strings", models.PositiveIntegerField(default=0)),
                ("peer_approved", models.PositiveIntegerField(default=0)),
                ("self_approved", models.PositiveIntegerField(default=0)),
                ("rejected", models.PositiveIntegerField(default=0)),
                ("new_suggestions", models.PositiveIntegerField(default=0)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.locale"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
