# Generated by Django 3.2.4 on 2021-08-24 06:45

import datetime
from django.db import migrations, models
import pontoon.insights.models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0002_project_projectlocale"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="active_users_last_12_months",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="active_users_last_3_months",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="active_users_last_6_months",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="active_users_last_month",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="human_translations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="machinery_translations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="new_source_strings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="new_suggestions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="peer_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="rejected",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="self_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="total_contributors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="total_managers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="total_reviewers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="unreviewed_suggestions_lifespan",
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name="localeinsightssnapshot",
            name="unreviewed_suggestions_lifespan",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
