# Generated by Django 3.2.4 on 2021-09-30 13:39

import datetime
import pontoon.insights.models

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0004_project_insights_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="active_users_last_12_months",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="active_users_last_3_months",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="active_users_last_6_months",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="active_users_last_month",
            field=models.JSONField(
                default=pontoon.insights.models.active_users_default
            ),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="human_translations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="machinery_translations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="new_source_strings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="new_suggestions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="peer_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="rejected",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="self_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="total_contributors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="total_managers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="total_reviewers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="unreviewed_suggestions_lifespan",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
