# Generated by Django 3.2.15 on 2023-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0010_fuzzy_to_pretranslated_strings"),
    ]

    operations = [
        migrations.AddField(
            model_name="localeinsightssnapshot",
            name="time_to_review_pretranslations",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="time_to_review_pretranslations",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="time_to_review_pretranslations",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="localeinsightssnapshot",
            name="time_to_review_suggestions",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="projectinsightssnapshot",
            name="time_to_review_suggestions",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="projectlocaleinsightssnapshot",
            name="time_to_review_suggestions",
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
