# Generated by Django 3.2.15 on 2023-08-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0012_time_to_review_pretranslations_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="localeinsightssnapshot",
            name="pretranslations_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="localeinsightssnapshot",
            name="pretranslations_chrf_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="localeinsightssnapshot",
            name="pretranslations_new",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="localeinsightssnapshot",
            name="pretranslations_rejected",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="pretranslations_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="pretranslations_chrf_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="pretranslations_new",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectinsightssnapshot",
            name="pretranslations_rejected",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="pretranslations_approved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="pretranslations_chrf_score",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="pretranslations_new",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectlocaleinsightssnapshot",
            name="pretranslations_rejected",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
