# Generated by Django 5.2.14 on 2026-06-24 04:38

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0020_fix_pretranslations_chrf_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocaleHealthSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField()),
                (
                    "completion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("key_projects_enabled", models.PositiveIntegerField(default=0)),
                ("active_managers", models.PositiveIntegerField(default=0)),
                ("active_translators", models.PositiveIntegerField(default=0)),
                ("active_contributors", models.PositiveIntegerField(default=0)),
                ("all_contributors", models.PositiveIntegerField(default=0)),
                ("new_signups", models.PositiveIntegerField(default=0)),
                (
                    "completion_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "key_projects_enabled_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "active_managers_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "active_translators_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "active_contributors_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "all_contributors_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "new_signups_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("chs", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.locale"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at", "locale"],
                        name="insights_lo_created_b801b7_idx",
                    )
                ],
                "unique_together": {("locale", "created_at")},
            },
        ),
    ]
