# Generated by Django 5.2.14 on 2026-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0021_localechssnapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localechssnapshot",
            name="active_contributors_200_approved",
        ),
        migrations.AddField(
            model_name="localechssnapshot",
            name="all_contributors",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
