# Generated by Django 5.2.14 on 2026-06-09 19:14

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0113_userbanlog"),
        (
            "insights",
            "0022_remove_localechssnapshot_active_contributors_200_approved_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LocaleHealthSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField()),
                ("completion", models.FloatField(default=0.0)),
                ("key_projects_enabled", models.PositiveIntegerField(default=0)),
                ("active_managers", models.PositiveIntegerField(default=0)),
                ("active_translators", models.PositiveIntegerField(default=0)),
                ("active_contributors", models.PositiveIntegerField(default=0)),
                ("all_contributors", models.PositiveIntegerField(default=0)),
                ("new_signups", models.PositiveIntegerField(default=0)),
                ("completion_score", models.FloatField(default=0.0)),
                ("key_projects_enabled_score", models.PositiveIntegerField(default=0)),
                ("active_managers_score", models.PositiveIntegerField(default=0)),
                ("active_translators_score", models.PositiveIntegerField(default=0)),
                ("active_contributors_score", models.PositiveIntegerField(default=0)),
                ("all_contributors_score", models.PositiveIntegerField(default=0)),
                ("new_signups_score", models.PositiveIntegerField(default=0)),
                ("chs_score", models.FloatField(default=0.0)),
                (
                    "locale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.locale"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LocaleChsSnapshot",
        ),
        migrations.AddIndex(
            model_name="localehealthsnapshot",
            index=models.Index(
                fields=["created_at", "locale"], name="insights_lo_created_b801b7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="localehealthsnapshot",
            unique_together={("locale", "created_at")},
        ),
    ]
