# Generated by Django 5.2.14 on 2026-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0023_localehealthsnapshot_delete_localechssnapshot_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="localehealthsnapshot",
            old_name="chs_score",
            new_name="chs",
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="active_contributors_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="active_managers_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="active_translators_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="all_contributors_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="key_projects_enabled_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="new_signups_score",
            field=models.FloatField(default=0),
        ),
    ]
