# Generated by Django 5.2.14 on 2026-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insights", "0024_rename_chs_score_localehealthsnapshot_chs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="active_contributors_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="active_managers_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="active_translators_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="all_contributors_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="chs",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="completion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="completion_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="key_projects_enabled_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="localehealthsnapshot",
            name="new_signups_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
