# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def load_initial_data(apps, schema_editor):
    Locale = apps.get_model("base", "Locale")
    for locale_kwargs in LOCALES:
        Locale.objects.create(**locale_kwargs)

    Project = apps.get_model("base", "Project")
    project = Project.objects.create(
        name="Pontoon Intro",
        slug="pontoon-intro",
        url=settings.SITE_URL + "/intro/",
        links=True,
        repository_type="git",
        repository_url="https://github.com/mozilla/pontoon-intro.git",
        info_brief=(
            "This is a demo website, used for demonstration purposes "
            "only. You can translate on the website itself by double "
            "clicking on page elements. Access to advanced features "
            "like translation memory and machine translation is "
            "available by clicking on the menu icon in the top-left "
            "corner."
        ),
    )

    # The "historical" version of the Project model that this migration
    # uses has trouble working with the ManyToManyField on the Project
    # model. Our workaround is to use the auto-generated intermediate
    # model directly to create the relation between project and locales.
    locale = Locale.objects.get(code="en-GB")
    Project.locales.through.objects.create(project_id=project.id, locale_id=locale.id)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]


LOCALES = [
    {"code": "af", "name": "Afrikaans", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "af-ZA", "name": "Afrikaans"},
    {"code": "ak", "name": "Akan", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "sq", "name": "Albanian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "sq-AL", "name": "Albanian"},
    {"code": "aln", "name": "Albanian Gheg"},
    {"code": "am", "name": "Amharic", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "am-ET", "name": "Amharic"},
    {
        "code": "ar",
        "name": "Arabic",
        "nplurals": "6",
        "plural_rule": "(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5)",
    },
    {"code": "ar-SA", "name": "Arabic"},
    {"code": "an", "name": "Aragonese", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "hy", "name": "Armenian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "hy-AM", "name": "Armenian"},
    {"code": "as", "name": "Assamese"},
    {"code": "as-IN", "name": "Assamese"},
    {"code": "ast", "name": "Asturian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "az", "name": "Azerbaijani", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "az-AZ", "name": "Azerbaijani"},
    {"code": "bal", "name": "Balochi"},
    {"code": "eu", "name": "Basque", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "eu-ES", "name": "Basque"},
    {
        "code": "be",
        "name": "Belarusian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "be-BY", "name": "Belarusian"},
    {"code": "be@tarask", "name": "Belarusian"},
    {"code": "bn", "name": "Bengali", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "bn-BD", "name": "Bengali", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "bn-IN", "name": "Bengali", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "bs",
        "name": "Bosnian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "bs-BA", "name": "Bosnian"},
    {"code": "br", "name": "Breton", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "bg", "name": "Bulgarian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "bg-BG", "name": "Bulgarian"},
    {"code": "my", "name": "Burmese", "nplurals": "1", "plural_rule": "0"},
    {"code": "my-MM", "name": "Burmese"},
    {"code": "ca", "name": "Catalan", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ca-ES", "name": "Catalan"},
    {"code": "ca@valencia", "name": "Catalan"},
    {
        "code": "hne",
        "name": "Chhattisgarhi",
        "nplurals": "2",
        "plural_rule": "(n != 1)",
    },
    {"code": "zh", "name": "Chinese", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "zh-CN", "name": "Chinese", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "zh-CN.GB2312", "name": "Chinese"},
    {"code": "zh-HK", "name": "Chinese", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "zh-TW", "name": "Chinese", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "zh-TW.Big5", "name": "Chinese"},
    {
        "code": "kw",
        "name": "Cornish",
        "nplurals": "4",
        "plural_rule": "(n==1) ? 0 : (n==2) ? 1 : (n == 3) ? 2 : 3",
    },
    {"code": "crh", "name": "Crimean Turkish"},
    {
        "code": "hr",
        "name": "Croatian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "hr-HR", "name": "Croatian"},
    {
        "code": "cs",
        "name": "Czech",
        "nplurals": "3",
        "plural_rule": "(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2",
    },
    {"code": "cs-CZ", "name": "Czech"},
    {"code": "da", "name": "Danish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "da-DK", "name": "Danish"},
    {"code": "nl", "name": "Dutch", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "nl-BE", "name": "Dutch"},
    {"code": "nl-NL", "name": "Dutch"},
    {"code": "dz", "name": "Dzongkha", "nplurals": "1", "plural_rule": "0"},
    {"code": "dz-BT", "name": "Dzongkha"},
    {"code": "en", "name": "English", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "en-AU", "name": "English", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "en-CA", "name": "English", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "en-IE", "name": "English", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "en-ZA", "name": "English", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "en-GB", "name": "English", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "en-US", "name": "English", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "eo", "name": "Esperanto", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "et", "name": "Estonian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "et-EE", "name": "Estonian"},
    {"code": "fo", "name": "Faroese", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "fo-FO", "name": "Faroese"},
    {"code": "fil", "name": "Filipino", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "fi", "name": "Finnish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "fi-FI", "name": "Finnish"},
    {"code": "frp", "name": "Franco-Proven\xe7al"},
    {"code": "fr", "name": "French", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "fr-CA", "name": "French"},
    {"code": "fr-FR", "name": "French"},
    {"code": "fr-CH", "name": "French"},
    {"code": "fur", "name": "Friulian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ff", "name": "Fulah", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "gd",
        "name": "Gaelic, Scottish",
        "nplurals": "4",
        "plural_rule": "(n==1 || n==11) ? 0 : (n==2 || n==12) ? 1 : (n > 2 && n < 20) ? 2 : 3",
    },
    {"code": "gl", "name": "Galician", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "gl-ES", "name": "Galician"},
    {"code": "ka", "name": "Georgian", "nplurals": "1", "plural_rule": "0"},
    {"code": "ka-GE", "name": "Georgian"},
    {"code": "de", "name": "German", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "de-DE", "name": "German"},
    {"code": "de-CH", "name": "German"},
    {"code": "el", "name": "Greek", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "el-GR", "name": "Greek"},
    {"code": "gu", "name": "Gujarati", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "gu-IN", "name": "Gujarati", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "gun", "name": "Gun", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "ht", "name": "Haitian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ht-HT", "name": "Haitian"},
    {"code": "ha", "name": "Hausa", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "he", "name": "Hebrew", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "he-IL", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "hi-IN", "name": "Hindi", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "hu", "name": "Hungarian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "hu-HU", "name": "Hungarian"},
    {
        "code": "is",
        "name": "Icelandic",
        "nplurals": "2",
        "plural_rule": "(n%10!=1 || n%100==11)",
    },
    {"code": "is-IS", "name": "Icelandic"},
    {"code": "ig", "name": "Igbo"},
    {"code": "ilo", "name": "Iloko"},
    {"code": "id", "name": "Indonesian", "nplurals": "1", "plural_rule": "0"},
    {"code": "id-ID", "name": "Indonesian"},
    {"code": "ia", "name": "Interlingua", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "ga",
        "name": "Irish",
        "nplurals": "5",
        "plural_rule": "n==1 ? 0 : n==2 ? 1 : n<7 ? 2 : n<11 ? 3 : 4",
    },
    {"code": "ga-IE", "name": "Irish"},
    {"code": "it", "name": "Italian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "it-IT", "name": "Italian"},
    {"code": "ja", "name": "Japanese", "nplurals": "1", "plural_rule": "0"},
    {"code": "ja-JP", "name": "Japanese"},
    {"code": "jv", "name": "Javanese", "nplurals": "2", "plural_rule": "(n != 0)"},
    {"code": "kn", "name": "Kannada", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "kn-IN", "name": "Kannada"},
    {"code": "ks", "name": "Kashmiri"},
    {"code": "ks-IN", "name": "Kashmiri"},
    {
        "code": "csb",
        "name": "Kashubian",
        "nplurals": "3",
        "plural_rule": "(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "kk", "name": "Kazakh", "nplurals": "1", "plural_rule": "0"},
    {"code": "kk-KZ", "name": "Kazakh"},
    {"code": "km", "name": "Khmer", "nplurals": "1", "plural_rule": "0"},
    {"code": "km-KH", "name": "Khmer"},
    {"code": "rw", "name": "Kinyarwanda", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ky", "name": "Kirgyz", "nplurals": "1", "plural_rule": "0"},
    {"code": "tlh", "name": "Klingon"},
    {"code": "ko", "name": "Korean", "nplurals": "1", "plural_rule": "0"},
    {"code": "ko-KR", "name": "Korean"},
    {"code": "ku", "name": "Kurdish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ku-IQ", "name": "Kurdish"},
    {"code": "lo", "name": "Lao", "nplurals": "1", "plural_rule": "0"},
    {"code": "lo-LA", "name": "Lao"},
    {"code": "la", "name": "Latin"},
    {
        "code": "lv",
        "name": "Latvian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2)",
    },
    {"code": "lv-LV", "name": "Latvian"},
    {"code": "lij", "name": "Ligurian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "li", "name": "Limburgian"},
    {"code": "ln", "name": "Lingala", "nplurals": "2", "plural_rule": "(n > 1)"},
    {
        "code": "lt",
        "name": "Lithuanian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && (n%100<10 or n%100>=20) ? 1 : 2)",
    },
    {"code": "lt-LT", "name": "Lithuanian"},
    {"code": "nds", "name": "Low German"},
    {"code": "lb", "name": "Luxembourgish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "mk",
        "name": "Macedonian",
        "nplurals": "2",
        "plural_rule": "(n==1 || n%10==1 ? 0 : 1)",
    },
    {"code": "mk-MK", "name": "Macedonian"},
    {"code": "mai", "name": "Maithili", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "mg", "name": "Malagasy", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "ms", "name": "Malay", "nplurals": "1", "plural_rule": "0"},
    {"code": "ml", "name": "Malayalam", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ml-IN", "name": "Malayalam"},
    {"code": "ms-MY", "name": "Malay"},
    {
        "code": "mt",
        "name": "Maltese",
        "nplurals": "4",
        "plural_rule": "(n==1 ? 0 : n==0 || ( n%100>1 && n%100<11) ? 1 : (n%100>10 && n%100<20 ) ? 2 : 3)",
    },
    {"code": "mt-MT", "name": "Maltese"},
    {"code": "mi", "name": "Maori", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "arn", "name": "Mapudungun", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "mr", "name": "Marathi", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "mr-IN", "name": "Marathi"},
    {"code": "mn", "name": "Mongolian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "mn-MN", "name": "Mongolian"},
    {"code": "nah", "name": "Nahuatl", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "nr", "name": "Ndebele, South"},
    {"code": "nap", "name": "Neapolitan", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ne", "name": "Nepali", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ne-NP", "name": "Nepali"},
    {"code": "se", "name": "Northern Sami", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "nso",
        "name": "Northern Sotho",
        "nplurals": "2",
        "plural_rule": "(n != 1)",
    },
    {"code": "no", "name": "Norwegian", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "nb",
        "name": "Norwegian Bokm\xe5l",
        "nplurals": "2",
        "plural_rule": "(n != 1)",
    },
    {"code": "nb-NO", "name": "Norwegian Bokm\xe5l"},
    {"code": "no-NO", "name": "Norwegian"},
    {
        "code": "nn",
        "name": "Norwegian Nynorsk",
        "nplurals": "2",
        "plural_rule": "(n != 1)",
    },
    {"code": "nn-NO", "name": "Norwegian Nynorsk"},
    {"code": "oc", "name": "Occitan", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "or", "name": "Oriya", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "or-IN", "name": "Oriya"},
    {"code": "pa", "name": "Panjabi", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "pa-IN", "name": "Panjabi"},
    {"code": "pap", "name": "Papiamento", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "fa", "name": "Persian", "nplurals": "1", "plural_rule": "0"},
    {"code": "fa-IR", "name": "Persian"},
    {"code": "pms", "name": "Piemontese", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "pl",
        "name": "Polish",
        "nplurals": "3",
        "plural_rule": "(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "pl-PL", "name": "Polish"},
    {"code": "pt", "name": "Portuguese", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "pt-BR", "name": "Portuguese", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "pt-PT", "name": "Portuguese"},
    {"code": "ps", "name": "Pushto", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "ro",
        "name": "Romanian",
        "nplurals": "3",
        "plural_rule": "(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2)",
    },
    {"code": "ro-RO", "name": "Romanian"},
    {"code": "rm", "name": "Romansh", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "ru",
        "name": "Russian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "ru-RU", "name": "Russian"},
    {"code": "sm", "name": "Samoan"},
    {"code": "sc", "name": "Sardinian"},
    {"code": "sco", "name": "Scots", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "sr",
        "name": "Serbian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {
        "code": "sr@latin",
        "name": "Serbian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "sr-RS@latin", "name": "Serbian"},
    {"code": "sr-RS", "name": "Serbian"},
    {"code": "sn", "name": "Shona"},
    {"code": "si", "name": "Sinhala", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "si-LK", "name": "Sinhala"},
    {
        "code": "sk",
        "name": "Slovak",
        "nplurals": "3",
        "plural_rule": "(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2",
    },
    {"code": "sk-SK", "name": "Slovak"},
    {
        "code": "sl",
        "name": "Slovenian",
        "nplurals": "4",
        "plural_rule": "(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3)",
    },
    {
        "code": "sl-SI",
        "name": "Slovenian",
        "nplurals": "4",
        "plural_rule": "(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3)",
    },
    {"code": "so", "name": "Somali", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "son", "name": "Songhay", "nplurals": "2", "plural_rule": "(n != 1)"},
    {
        "code": "st",
        "name": "Sotho, Southern",
        "nplurals": "2",
        "plural_rule": "(n != 1)",
    },
    {"code": "st-ZA", "name": "Sotho, Southern"},
    {"code": "es-AR", "name": "Spanish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "es-BO", "name": "Spanish"},
    {"code": "es", "name": "Spanish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "es-CL", "name": "Spanish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "es-CO", "name": "Spanish"},
    {"code": "es-CR", "name": "Spanish"},
    {"code": "es-DO", "name": "Spanish"},
    {"code": "es-EC", "name": "Spanish"},
    {"code": "es-SV", "name": "Spanish"},
    {"code": "es-MX", "name": "Spanish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "es-NI", "name": "Spanish"},
    {"code": "es-PA", "name": "Spanish"},
    {"code": "es-PY", "name": "Spanish"},
    {"code": "es-PE", "name": "Spanish"},
    {"code": "es-PR", "name": "Spanish"},
    {"code": "es-ES", "name": "Spanish"},
    {"code": "es-UY", "name": "Spanish"},
    {"code": "es-VE", "name": "Spanish"},
    {"code": "su", "name": "Sundanese", "nplurals": "1", "plural_rule": "0"},
    {"code": "sw", "name": "Swahili", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "sw-KE", "name": "Swahili"},
    {"code": "sv", "name": "Swedish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "sv-FI", "name": "Swedish"},
    {"code": "sv-SE", "name": "Swedish", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "tl", "name": "Tagalog"},
    {"code": "tl-PH", "name": "Tagalog"},
    {"code": "tg", "name": "Tajik", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "tg-TJ", "name": "Tajik"},
    {"code": "ta", "name": "Tamil", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ta-IN", "name": "Tamil", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ta-LK", "name": "Tamil"},
    {"code": "tt", "name": "Tatar", "nplurals": "1", "plural_rule": "0"},
    {"code": "te", "name": "Telugu", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "te-IN", "name": "Telugu"},
    {"code": "th", "name": "Thai", "nplurals": "1", "plural_rule": "0"},
    {"code": "th-TH", "name": "Thai"},
    {"code": "bo", "name": "Tibetan", "nplurals": "1", "plural_rule": "0"},
    {"code": "bo-CN", "name": "Tibetan"},
    {"code": "ti", "name": "Tigrinya", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "to", "name": "Tongan"},
    {"code": "tr", "name": "Turkish", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "tr-TR", "name": "Turkish"},
    {"code": "tk", "name": "Turkmen", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ug", "name": "Uighur", "nplurals": "1", "plural_rule": "0"},
    {
        "code": "uk",
        "name": "Ukrainian",
        "nplurals": "3",
        "plural_rule": "(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)",
    },
    {"code": "uk-UA", "name": "Ukrainian"},
    {
        "code": "hsb",
        "name": "Upper Sorbian",
        "nplurals": "4",
        "plural_rule": "(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3)",
    },
    {"code": "ur", "name": "Urdu", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "ur-PK", "name": "Urdu"},
    {"code": "uz", "name": "Uzbek", "nplurals": "2", "plural_rule": "(n > 1)"},
    {"code": "ve", "name": "Venda"},
    {"code": "vi", "name": "Vietnamese", "nplurals": "1", "plural_rule": "0"},
    {"code": "vi-VN", "name": "Vietnamese"},
    {"code": "vls", "name": "Vlaams"},
    {"code": "wa", "name": "Walloon", "nplurals": "2", "plural_rule": "(n > 1)"},
    {
        "code": "cy",
        "name": "Welsh",
        "nplurals": "4",
        "plural_rule": "(n==1) ? 0 : (n==2) ? 1 : (n != 8 && n != 11) ? 2 : 3",
    },
    {"code": "cy-GB", "name": "Welsh"},
    {
        "code": "fy",
        "name": "Western Frisian",
        "nplurals": "2",
        "plural_rule": "(n != 1)",
    },
    {"code": "fy-NL", "name": "Western Frisian"},
    {"code": "wo", "name": "Wolof", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "wo-SN", "name": "Wolof"},
    {"code": "xh", "name": "Xhosa", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "yo", "name": "Yoruba", "nplurals": "2", "plural_rule": "(n != 1)"},
    {"code": "zu", "name": "Zulu"},
    {"code": "zu-ZA", "name": "Zulu"},
    {
        "code": "dsb",
        "name": "Lower Sorbian",
        "nplurals": "4",
        "plural_rule": "(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3)",
    },
]
