# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 18:21
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# This is needed for https://bugzilla.mozilla.org/show_bug.cgi?id=1671836
# This and its calls in this migration can be removed once this migration is squashed.
class TryRemoveIndex(migrations.RemoveIndex):
    """
    Removes an index from a model if the index is present. Otherwise, nothing happens.
    """

    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except ValueError:
            pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except ValueError:
            pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # Don't do anything, since we don't want to recreate the index
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_squashed_0154_auto_20200206_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionchangelog",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changed_permissions_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="permissionchangelog",
            name="performed_on",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permisions_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="\n        L10n driver in charge of the project\n    ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="approved_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="rejected_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="unapproved_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unapproved_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="unrejected_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unrejected_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        TryRemoveIndex(
            model_name="translation", name="base_transl_entity__fbea1e_partial",
        ),
        TryRemoveIndex(
            model_name="translation", name="base_transl_entity__ed9592_partial",
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                condition=models.Q(active=True),
                fields=("entity", "locale", "plural_form", "active"),
                name="entity_locale_plural_form_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("plural_form__isnull", True)),
                fields=("entity", "locale", "active"),
                name="entity_locale_active",
            ),
        ),
        migrations.AlterField(
            model_name="translationmemoryentry",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memory_entries",
                to="base.Project",
            ),
        ),
    ]
