# Generated by Django 2.2.11 on 2020-05-16 22:22

from django.db import migrations


def make_projects_public(apps, schema_editor):
    """Old projects were public by default."""

    Project = apps.get_model("base", "Project")
    Project.objects.update(visibility="public")


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_add_visibility_field_to_project"),
    ]

    operations = [migrations.RunPython(make_projects_public, migrations.RunPython.noop)]
