# Generated by Django 2.2.11 on 2020-07-02 18:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_auto_20200703_0710"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="machinery_sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("translation-memory", "Translation Memory"),
                        ("google-translate", "Google Translate"),
                        ("microsoft-translator", "Microsoft Translator"),
                        ("microsoft-terminology", "Microsoft"),
                        ("transvision", "Mozilla"),
                        ("caighdean", "Caighdean"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
