# Generated by Django 2.2.13 on 2020-07-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200703_0710'),
        ('base', '0006_auto_20200702_1656'),
    ]

    operations = [
    ]
