# Generated by Django 2.2.13 on 2020-07-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_machinery_sources_translation'),
        ('base', '0006_auto_20200702_1656'),
    ]

    operations = [
    ]
