# Generated by Django 2.2.13 on 2020-08-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_merge_20200709_0813'),
        ('base', '0008_add_systran_locales'),
    ]

    operations = [
    ]
