# Generated by Django 2.2.13 on 2020-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_change_pontoon_users_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
