# Generated by Django 2.2.13 on 2020-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_comment_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="permalink_prefix",
            field=models.CharField(
                blank=True,
                help_text="\n        A URL prefix for downloading localized files. For GitHub repositories,\n        select any localized file on GitHub, click Raw and replace locale code\n        and the following bits in the URL with `{locale_code}`. If you use a\n        project configuration file, you need to provide the path to the raw TOML\n        file on GitHub.\n    ",
                max_length=2000,
                verbose_name="Download prefix or path to TOML file",
            ),
        ),
    ]
