# Generated by Django 3.2 on 2021-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_auto_20210310_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_dismissed_addon_promotion",
            field=models.BooleanField(default=False),
        ),
    ]
