# Generated by Django 3.2.4 on 2021-09-02 06:28

from django.db import migrations, models
import pontoon.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_populate_entity_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locale",
            name="cldr_plurals",
            field=models.CharField(
                blank=True,
                help_text='\n        A comma separated list of\n        <a href="http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html">\n        CLDR plural categories</a>, where 0 represents zero, 1 one, 2 two, 3 few, 4 many, and 5 other.\n        E.g. 1,5\n        ',
                max_length=11,
                validators=[pontoon.base.models.validate_cldr],
                verbose_name="CLDR Plurals",
            ),
        ),
    ]
