# Generated by Django 3.2.4 on 2021-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_alter_locale_cldr_plurals"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="comment_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="new_string_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="project_deadline_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unreviewed_suggestion_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
