# Generated by Django 3.2.10 on 2022-03-15 14:08

from django.db import migrations, models
import pontoon.base.models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_notification_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="url",
            field=models.CharField(
                max_length=2000,
                validators=[pontoon.base.models.repository_url_validator],
                verbose_name="URL",
            ),
        ),
    ]
