# Generated by Django 3.2.10 on 2022-03-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_alter_repository_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="review_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
