# Generated by Django 3.2.10 on 2022-03-23 22:54

from django.db import migrations


def adjust_stats(model):
    model.fuzzy_strings = 0
    model.save(update_fields=["fuzzy_strings"])


def fuzzy_to_missing(apps, schema_editor):
    ProjectLocale = apps.get_model("base", "ProjectLocale")
    TranslatedResource = apps.get_model("base", "TranslatedResource")

    for tr in TranslatedResource.objects.filter(fuzzy_strings__gt=0):
        project = tr.resource.project
        locale = tr.locale

        adjust_stats(tr)
        adjust_stats(project)
        adjust_stats(locale)

        try:
            project_locale = ProjectLocale.objects.get(project=project, locale=locale)
            adjust_stats(project_locale)
        except ProjectLocale.DoesNotExist:
            return None


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_reviewed_suggestions"),
    ]

    operations = [
        migrations.RunPython(
            code=fuzzy_to_missing,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
