# Generated by Django 3.2.10 on 2022-03-24 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0023_fuzzy_to_missing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locale",
            old_name="fuzzy_strings",
            new_name="pretranslated_strings",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="fuzzy_strings",
            new_name="pretranslated_strings",
        ),
        migrations.RenameField(
            model_name="projectlocale",
            old_name="fuzzy_strings",
            new_name="pretranslated_strings",
        ),
        migrations.RenameField(
            model_name="translatedresource",
            old_name="fuzzy_strings",
            new_name="pretranslated_strings",
        ),
        migrations.AddField(
            model_name="translation",
            name="pretranslated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name="translation",
            index_together={
                ("entity", "user", "approved", "pretranslated"),
                ("locale", "user", "entity"),
                ("date", "locale"),
                ("entity", "locale", "approved"),
                ("entity", "locale", "fuzzy"),
                ("entity", "locale", "pretranslated"),
            },
        ),
    ]
