# Generated by Django 3.2.13 on 2022-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_remove_tm_entries_of_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlocale",
            name="pretranslation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
