# Generated by Django 3.2.13 on 2022-05-05 08:31

from django.db import migrations


def propagate_pretranslation_enabled(apps, schema_editor):
    """
    Projects that have pretranslation enabled need to keep it enabled for all locales.
    """
    ProjectLocale = apps.get_model("base", "ProjectLocale")
    ProjectLocale.objects.filter(project__pretranslation_enabled=True).update(
        pretranslation_enabled=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_projectlocale_pretranslation_enabled"),
    ]

    operations = [
        migrations.RunPython(
            code=propagate_pretranslation_enabled,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
