# Generated by Django 3.2.13 on 2022-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0027_keep_pretranslation_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="new_contributor_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
