# Generated by Django 3.2.14 on 2022-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_userprofile_contact_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="matrix",
            new_name="chat",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chat",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Chat username"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="GitHub username"
            ),
        ),
    ]
