# Generated by Django 3.2.14 on 2022-08-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_rename_matrix_to_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="visibility_approval",
            field=models.CharField(
                choices=[
                    ("Public", "Public"),
                    ("Translators", "Users with translator rights"),
                ],
                default="Public",
                max_length=20,
                verbose_name="Approval rate",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="visibility_self_approval",
            field=models.CharField(
                choices=[
                    ("Public", "Public"),
                    ("Translators", "Users with translator rights"),
                ],
                default="Public",
                max_length=20,
                verbose_name="Self-approval rate",
            ),
        ),
    ]
