# Generated by Django 3.2.15 on 2022-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_alter_locale_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="system_user",
            field=models.BooleanField(default=False),
        ),
    ]
