# Generated by Django 3.2.15 on 2022-11-30 20:32
from django.db import migrations


def mark_system_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("base", "UserProfile")

    user = User.objects.filter(email="pontoon-sync@example.com").first()
    user_profile = UserProfile.objects.filter(user=user).first()
    if user and user_profile:
        user_profile.system_user = True
        user_profile.save

    user = User.objects.filter(email="pontoon-gt@example.com").first()
    user_profile = UserProfile.objects.filter(user=user).first()
    if user and user_profile:
        user_profile.system_user = True
        user_profile.save

    user = User.objects.filter(email="pontoon-tm@example.com").first()
    user_profile = UserProfile.objects.filter(user=user).first()
    if user and user_profile:
        user_profile.system_user = True
        user_profile.save


def revert_mark_system_users(apps, schema_editor):
    User = apps.get_model("auth", "User")

    user = User.objects.filter(email="pontoon-sync@example.com").first()
    user_profile = UserProfile.objects.filter(user=user).first()
    if user and user_profile:
        user_profile.system_user = None
        user_profile.save

    user = User.objects.filter(email="pontoon-gt@example.com").first()
    user_profile = UserProfile.objects.filter(user=user).first()
    if user and user_profile:
        user_profile.system_user = None
        user_profile.save

    user = User.objects.filter(email="pontoon-tm@example.com").first()
    user_profile = UserProfile.objects.filter(user=user).first()
    if user and user_profile:
        user_profile.system_user = None
        user_profile.save


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0037_userprofile_system_user"),
    ]

    operations = [
        migrations.RunPython(
            code=mark_system_users,
            reverse_code=revert_mark_system_users,
        ),
    ]
