# Generated by Django 3.2.15 on 2023-02-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_alter_locale_population"),
        ("base", "0038_mark_system_users"),
    ]

    operations = []
