# Generated by Django 3.2.15 on 2023-02-23 16:02
from django.db import migrations
from pontoon.base.models import Project, Resource, Entity, ChangedEntityLocale


def remove_changed_entity_locale_entries_for_repository_projects(apps, schema_editor):
    ChangedEntityLocale.objects.filter(
        entity__resource__project__data_source=Project.DataSource.DATABASE
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0039_mark_system_users"),
    ]

    operations = [
        migrations.RunPython(
            code=remove_changed_entity_locale_entries_for_repository_projects,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
