# Generated by Django 3.2.15 on 2023-02-23 16:02
from django.db import migrations
from pontoon.base.models import Project, Resource, Entity, ChangedEntityLocale


def remove_changed_entity_locale_entries_for_repository_projects(apps, schema_editor):
    projects = Project.objects.filter(data_source=Project.DataSource.DATABASE)
    resources = Resource.objects.filter(project__in=projects)
    entities = Entity.objects.filter(resource__in=resources)
    ChangedEntityLocale.objects.filter(entity__in=entities).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0039_mark_system_users"),
    ]

    operations = [
        migrations.RunPython(
            code=remove_changed_entity_locale_entries_for_repository_projects,
        ),
    ]
