# Generated by Django 3.2.15 on 2023-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0042_locale_accesskey_localization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locale",
            name="accesskey_localization",
            field=models.BooleanField(
                default=True,
                help_text="\n        Allow localization of access keys if they are part of a string.\n        Some locales don't translate access keys, mostly because they use non-Latin scripts.\n    ",
                verbose_name="Access key localization",
            ),
        ),
    ]
