# Generated by Django 3.2.15 on 2023-05-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0043_alter_locale_accesskey_localization"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subpage",
        ),
    ]
