# Generated by Django 3.2.15 on 2023-05-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0044_delete_subpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="links",
        ),
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="width",
        ),
    ]
