# Generated by Django 3.2.15 on 2023-10-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0046_projectslughistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="themes",
            field=models.CharField(
                choices=[("Dark", "Dark"), ("Light", "Light"), ("System", "System")],
                default="Dark",
                max_length=20,
            ),
        ),
    ]
