# Generated by Django 3.2.15 on 2023-10-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_userprofile_themes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="themes",
            new_name="theme",
        ),
    ]
