# Generated by Django 3.2.24 on 2024-03-08 14:29

from django.db import migrations


def populate_resource_order(apps, schema_editor):
    Project = apps.get_model("base", "Project")
    Resource = apps.get_model("base", "Resource")
    projects = Project.objects.all()

    ordered_resources = []

    for p in projects.prefetch_related("resources"):
        resources = p.resources.all().order_by("path")
        for idx, r in enumerate(resources):
            r.order = idx
            ordered_resources.append(r)

    Resource.objects.bulk_update(ordered_resources, ["order"])


def reset_resource_order(apps, schema_editor):
    Resource = apps.get_model("base", "Resource")
    Resource.objects.update(order=0)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0054_resource_order"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_resource_order,
            reverse_code=reset_resource_order,
        ),
    ]
