# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0055_populate_denormalized_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="links",
            field=models.BooleanField(
                default=False,
                verbose_name=b"Keep links on the project website clickable",
            ),
        ),
    ]
