# Generated by Django 3.2.24 on 2024-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0056_remove_fuzzy_and_non-approved_tm_entries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translation",
            name="extra",
        ),
        migrations.AlterField(
            model_name="resource",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dtd", "dtd"),
                    ("ftl", "ftl"),
                    ("inc", "inc"),
                    ("ini", "ini"),
                    ("json", "json"),
                    ("po", "po"),
                    ("properties", "properties"),
                    ("xlf", "xliff"),
                    ("xliff", "xliff"),
                    ("xml", "xml"),
                ],
                max_length=20,
                verbose_name="Format",
            ),
        ),
    ]
