# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0058_rename_stats_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatedresource",
            name="total_strings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
