# Generated by Django 4.2.11 on 2024-05-09 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0059_alter_translation_machinery_sources"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="entity",
            new_name="base_entity_resourc_f99fa1_idx",
            old_fields=("resource", "obsolete", "string_plural"),
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="base_transl_date_30b613_idx",
            old_fields=("date", "locale"),
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="base_transl_entity__0b63dc_idx",
            old_fields=("entity", "user", "approved", "pretranslated"),
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="base_transl_entity__afb3fd_idx",
            old_fields=("entity", "locale", "approved"),
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="base_transl_entity__e71151_idx",
            old_fields=("entity", "locale", "fuzzy"),
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="base_transl_entity__30552e_idx",
            old_fields=("entity", "locale", "pretranslated"),
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="base_transl_approve_e5fa5f_idx",
            old_fields=("approved_date", "locale"),
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="base_transl_locale__0c5933_idx",
            old_fields=("locale", "user", "entity"),
        ),
    ]
