# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0060_auto_20160516_0849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="type",
            field=models.CharField(
                choices=[(b"git", b"Git"), (b"hg", b"HG"), (b"svn", b"SVN")],
                default=b"git",
                max_length=255,
            ),
        ),
    ]
