# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0061_auto_20160516_1140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"po", b"po"),
                    (b"xliff", b"xliff"),
                    (b"properties", b"properties"),
                    (b"dtd", b"dtd"),
                    (b"inc", b"inc"),
                    (b"ini", b"ini"),
                    (b"lang", b"lang"),
                    (b"l20n", b"l20n"),
                    (b"ftl", b"ftl"),
                ],
                max_length=20,
                verbose_name=b"Format",
            ),
        ),
    ]
