# Generated by Django 4.2.11 on 2024-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0061_userprofile_email_communications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_consent_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
