# Generated by Django 4.2.11 on 2024-05-22 12:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0062_userprofile_email_consent_dismissed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
