# Generated by Django 4.2.11 on 2024-05-20 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0062_userprofile_email_consent_dismissed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unsubscribe_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
