# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-20 14:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0063_remove_has_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="locales_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
