# Generated by Django 4.2.11 on 2024-05-20 15:38

import uuid

from django.db import migrations


def populate_unsubscribe_token(apps, schema_editor):
    UserProfile = apps.get_model("base", "UserProfile")
    for profile in UserProfile.objects.all():
        profile.unsubscribe_token = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0063_userprofile_unsubscribe_token"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_unsubscribe_token,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
