# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-13 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0064_userprofile_locales_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="unapproved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="unapproved_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unapprovers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
