# Generated by Django 4.2.16 on 2024-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0065_fix_projectlocale_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="community_builder_level",
            field=models.IntegerField(
                choices=[
                    (1, "Mentor Level 1"),
                    (3, "Mentor Level 3"),
                    (2, "Mentor Level 2"),
                    (0, "No Badge"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="review_master_level",
            field=models.IntegerField(
                choices=[
                    (0, "No Badge"),
                    (1, "Reviewer Level 1"),
                    (2, "Reviewer Level 2"),
                    (3, "Reviewer Level 3"),
                    (4, "Reviewer Level 4"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="translation_champion_level",
            field=models.IntegerField(
                choices=[
                    (0, "No Badge"),
                    (4, "Translator Level 4"),
                    (2, "Translator Level 2"),
                    (1, "Translator Level 1"),
                    (3, "Translator Level 3"),
                ],
                default=0,
            ),
        ),
    ]
