# Generated by Django 4.2.16 on 2024-10-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0065_fix_projectlocale_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="community_builder_level",
            field=models.IntegerField(
                choices=[
                    (0, "No Badge"),
                    (1, "Community Builder Level 1"),
                    (2, "Community Builder Level 2"),
                    (3, "Community Builder Level 3"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="review_master_level",
            field=models.IntegerField(
                choices=[
                    (0, "No Badge"),
                    (1, "Review Master Level 1"),
                    (2, "Review Master Level 2"),
                    (3, "Review Master Level 3"),
                    (4, "Review Master Level 4"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="translation_champion_level",
            field=models.IntegerField(
                choices=[
                    (0, "No Badge"),
                    (1, "Translation Champion Level 1"),
                    (2, "Translation Champion Level 2"),
                    (3, "Translation Champion Level 3"),
                    (4, "Translation Champion Level 4"),
                ],
                default=0,
            ),
        ),
    ]
