# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 20:47
from __future__ import unicode_literals

from django.db import migrations


def mark_browserid_accounts(apps, schema_editor):
    """
    Because of the our migration we have mark all accounts that were created
    by django-browserid and handle them in django-allauth.
    """
    UserProfile = apps.get_model("base", "UserProfile")
    UserProfile.objects.update(from_django_browserid=True)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0066_userprofile_from_django_browserid"),
    ]

    operations = [
        migrations.RunPython(mark_browserid_accounts, reverse_migration, elidable=True)
    ]
