# Generated by Django 4.2.16 on 2024-10-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0066_userprofile_community_builder_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="community_builder_level",
            field=models.IntegerField(
                choices=[
                    (0, "No Badge"),
                    (1, "Mentor Level 1"),
                    (2, "Mentor Level 2"),
                    (3, "Mentor Level 3"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="translation_champion_level",
            field=models.IntegerField(
                choices=[
                    (0, "No Badge"),
                    (1, "Translator Level 1"),
                    (2, "Translator Level 2"),
                    (3, "Translator Level 3"),
                    (4, "Translator Level 4"),
                ],
                default=0,
            ),
        ),
    ]
