# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import pontoon.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_migrate_old_django_browserid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='from_django_browserid',
        ),
        migrations.AlterField(
            model_name='locale',
            name='cldr_plurals',
            field=models.CommaSeparatedIntegerField(blank=True, help_text=b'\n        A comma separated list of <a href="https://www.unicode.org/cldr/charts/dev/supplemental/language_plural_rules.html">CLDR plural rules</a>,\n        where 0 represents zero, 1 one, 2 two, 3 few, 4 many, and 5 other.\n        E.g. 1,5\n        ', max_length=11, validators=[pontoon.base.models.validate_cldr], verbose_name=b'CLDR Plurals'),
        ),
        migrations.AlterField(
            model_name='locale',
            name='plural_rule',
            field=models.CharField(blank=True, help_text=b'\n        Plural rule is part of the plurals header in\n        <a href="https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms">Gettext PO files</a>,\n        that follows the <i>plural=</i> string, without the trailing semicolon.\n        E.g. (n != 1)\n        ', max_length=128),
        ),
    ]
