# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_migrate_old_django_browserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translation',
            name='unapproved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unapproved_translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
