# Generated by Django 4.2.16 on 2024-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0067_remove_userprofile_community_builder_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="comment_notifications_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="monthly_activity_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="new_contributor_notifications_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="new_string_notifications_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notification_email_frequency",
            field=models.CharField(
                choices=[("Daily", "Daily"), ("Weekly", "Weekly")],
                default="Weekly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="project_deadline_notifications_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="review_notifications_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unreviewed_suggestion_notifications_email",
            field=models.BooleanField(default=False),
        ),
    ]
