# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0069_auto_20161103_0829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="width",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=b"\n        Default website (iframe) width in pixels.\n        If set, sidebar will be opened by default.\n    ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="permalink_prefix",
            field=models.CharField(
                help_text=b"\n        A URL prefix for downloading localized files. For GitHub repositories,\n        select any localized file on GitHub, click Raw and replace locale code\n        and the following bits in the URL with `{locale_code}`.\n    ",
                max_length=2000,
                verbose_name=b"Download prefix",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="url",
            field=models.CharField(max_length=2000, verbose_name=b"URL"),
        ),
    ]
