# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0071_auto_20161123_2349"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectlocale",
            options={
                "permissions": (
                    ("can_translate_project_locale", "Can add translations"),
                )
            },
        ),
    ]
