# Generated by Django 4.2.17 on 2025-01-17 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0071_alter_repository_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locale",
            name="approved_strings",
        ),
        migrations.RemoveField(
            model_name="locale",
            name="pretranslated_strings",
        ),
        migrations.RemoveField(
            model_name="locale",
            name="strings_with_errors",
        ),
        migrations.RemoveField(
            model_name="locale",
            name="strings_with_warnings",
        ),
        migrations.RemoveField(
            model_name="locale",
            name="total_strings",
        ),
        migrations.RemoveField(
            model_name="locale",
            name="unreviewed_strings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="approved_strings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="pretranslated_strings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="strings_with_errors",
        ),
        migrations.RemoveField(
            model_name="project",
            name="strings_with_warnings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="total_strings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="unreviewed_strings",
        ),
        migrations.RemoveField(
            model_name="projectlocale",
            name="approved_strings",
        ),
        migrations.RemoveField(
            model_name="projectlocale",
            name="pretranslated_strings",
        ),
        migrations.RemoveField(
            model_name="projectlocale",
            name="strings_with_errors",
        ),
        migrations.RemoveField(
            model_name="projectlocale",
            name="strings_with_warnings",
        ),
        migrations.RemoveField(
            model_name="projectlocale",
            name="total_strings",
        ),
        migrations.RemoveField(
            model_name="projectlocale",
            name="unreviewed_strings",
        ),
    ]
