# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 23:37
from __future__ import unicode_literals

from django.db import migrations


def create_project_locale_permission(apps, schema_editor):
    """Create permissions for project/locale translators."""
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    project_locale_content_type, _ = ContentType.objects.get_or_create(
        app_label="base", model="projectlocale"
    )

    Permission.objects.get_or_create(
        codename="can_translate_project_locale",
        content_type=project_locale_content_type,
        name="Can translate a locale of project",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0072_auto_20161209_2330"),
        ("auth", "0006_require_contenttypes_0002"),
    ]

    operations = [
        migrations.RunPython(
            create_project_locale_permission, migrations.RunPython.noop
        )
    ]
