# Generated by Django 4.2.20 on 2025-04-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0072_remove_locale_approved_strings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionchangelog',
            name='performed_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
