# Generated by Django 4.2.20 on 2025-05-12 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0073_alter_permissionchangelog_performed_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="permalink_prefix",
        ),
    ]
