# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-12 13:23
from __future__ import unicode_literals

from django.db import migrations


def create_project_locale_groups(apps, schema_editor):
    """Create translators groups for every project locale object."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ProjectLocale = apps.get_model("base", "ProjectLocale")
    ContentType = apps.get_model("contenttypes", "ContentType")
    GroupObjectPermission = apps.get_model("guardian", "GroupObjectPermission")

    project_locale_ct = ContentType.objects.get(app_label="base", model="projectlocale")

    can_translate = Permission.objects.get(
        content_type=project_locale_ct, codename="can_translate_project_locale"
    )

    for project_locale in ProjectLocale.objects.all():
        translators_group = Group.objects.create(
            name="{}/{} translators".format(
                project_locale.project.slug, project_locale.locale.code,
            )
        )
        translators_group.permissions.add(can_translate)
        GroupObjectPermission.objects.create(
            object_pk=project_locale.pk,
            content_type=project_locale_ct,
            group=translators_group,
            permission=can_translate,
        )

        project_locale.translators_group = translators_group
        project_locale.save()


def remove_project_locale_groups(apps, schema):
    ProjectLocale = apps.get_model("base", "ProjectLocale")

    for project_locale in ProjectLocale.objects.all():
        project_locale.translators_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0074_projectlocale_translators_group"),
    ]

    operations = [
        migrations.RunPython(create_project_locale_groups, remove_project_locale_groups)
    ]
