# Generated by Django 4.2.20 on 2025-05-16 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0073_alter_userprofile_theme"),
        ("base", "0074_remove_repository_permalink_prefix"),
    ]

    operations = []
