# Generated by Django 4.2.20 on 2025-04-30 17:14

from django.db import migrations, models
from django.utils import timezone


def fix_nonplural_plural_form(apps, schema_editor):
    """
    De-activate and reject translations for gettext entities that
    were plural but have become non-plural since then.
    """
    Translation = apps.get_model("base", "Translation")
    translations = Translation.objects.filter(
        active=True, plural_form__isnull=False, entity__string_plural=""
    )
    for trans in translations:
        trans.active = False
        trans.fuzzy = False
        if trans.approved:
            trans.approved = False
            trans.rejected = True
            trans.rejected_date = timezone.now()
    Translation.objects.bulk_update(
        translations, ["active", "fuzzy", "approved", "rejected", "rejected_date"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0076_gettext_as_mf2"),
    ]

    operations = [
        migrations.RunPython(fix_nonplural_plural_form),
        migrations.RemoveConstraint(
            model_name="translation",
            name="entity_locale_plural_form_active",
        ),
        migrations.RemoveConstraint(
            model_name="translation",
            name="entity_locale_active",
        ),
        migrations.RemoveIndex(
            model_name="entity",
            name="base_entity_resourc_f99fa1_idx",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="string_plural",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="plural_form",
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["resource", "obsolete"], name="base_entity_resourc_16f82b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("entity", "locale", "active"),
                name="entity_locale_active",
            ),
        ),
    ]
