# Generated by Django 4.2.21 on 2025-05-20 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0075_fix_android_ini_properties"),
        ("base", "0076_remove_pontoon_intro_project"),
    ]

    operations = []
