# Generated by Django 4.2.17 on 2025-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0077_fix_android_newlines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light"), ("system", "System")],
                default="system",
                max_length=20,
            ),
        ),
    ]
