# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-27 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0079_auto_20170216_2320"),
    ]

    operations = [
        migrations.AddField(
            model_name="locale",
            name="direction",
            field=models.CharField(
                choices=[(b"ltr", b"left-to-right"), (b"rtl", b"right-to-left")],
                default=b"ltr",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="locale",
            name="population",
            field=models.PositiveIntegerField(
                default=0, help_text=b"\n        Number of native speakers.\n    "
            ),
        ),
        migrations.AddField(
            model_name="locale",
            name="script",
            field=models.CharField(default=b"Latin", max_length=128),
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, b"Lowest"),
                    (2, b"Low"),
                    (3, b"Normal"),
                    (4, b"High"),
                    (5, b"Highest"),
                ],
                default=3,
            ),
        ),
    ]
