# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0081_locale_script_direction_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="website",
            field=models.URLField(
                blank=True, max_length=2000, verbose_name=b"Public Repository Website"
            ),
        ),
    ]
