# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0083_populate_repository_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, b"Lowest"),
                    (2, b"Low"),
                    (3, b"Normal"),
                    (4, b"High"),
                    (5, b"Highest"),
                ],
                default=1,
            ),
        ),
    ]
