# Generated by Django 4.2.22 on 2025-07-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0083_gettext_as_mf2_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dtd", "dtd"),
                    ("ftl", "ftl"),
                    ("ini", "ini"),
                    ("json", "json"),
                    ("po", "po"),
                    ("properties", "properties"),
                    ("xlf", "xliff"),
                    ("xliff", "xliff"),
                    ("xml", "xml"),
                ],
                max_length=20,
                verbose_name="Format",
            ),
        ),
    ]
