# Generated by Django 4.2.22 on 2025-06-25 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0084_alter_resource_format"),
    ]

    operations = [
        migrations.RemoveField(model_name="entity", name="word_count"),
    ]
