# Generated by Django 4.2.22 on 2025-07-10 18:17

import django.contrib.postgres.fields
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0085_remove_entity_word_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="meta",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.TextField(), size=2
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="meta",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.TextField(), size=2
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "meta",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.TextField(), size=2
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="base.resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entity",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entities",
                to="base.section",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["resource"], name="base_sectio_resourc_f7dc62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["key", "comment"], name="base_sectio_key_a81a0b_idx"
            ),
        ),
    ]
