# Generated by Django 4.2.22 on 2025-07-10 18:17

from django.db import migrations


def set_section_and_resource_comments(apps, schema_editor):
    Entity = apps.get_model("base", "Entity")
    Section = apps.get_model("base", "Section")
    Resource = apps.get_model("base", "Resource")

    es = Entity.objects.exclude(group_comment="").order_by("resource", "order")
    sections = {}
    for entity in es:
        s_key = (entity.resource_id, entity.group_comment)
        section = sections.get(s_key, None)
        if section is None:
            section = Section(
                resource_id=entity.resource_id, key=[], comment=entity.group_comment
            )
            sections[s_key] = section
        entity.section = section
    Section.objects.bulk_create(sections.values())
    Entity.objects.bulk_update(es, ["section"])

    er = (
        Entity.objects.exclude(resource_comment="")
        .order_by("resource", "-date_created")
        .distinct("resource")
        .select_related("resource")
    )
    for entity in er:
        entity.resource.comment = entity.resource_comment
    Resource.objects.bulk_update((e.resource for e in er), ["comment"])


def reverse_section_and_resource_comments(apps, schema_editor):
    Entity = apps.get_model("base", "Entity")

    es = (
        Entity.objects.filter(section__isnull=False)
        .exclude(section__comment="")
        .order_by("section")
        .select_related("section")
    )
    for entity in es:
        entity.group_comment = entity.section.comment
    Entity.objects.bulk_update(es, ["group_comment"])

    er = (
        Entity.objects.exclude(resource__comment="")
        .order_by("resource")
        .select_related("resource")
    )
    for entity in er:
        entity.resource_comment = entity.resource.comment
    Entity.objects.bulk_update(er, ["resource_comment"])


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0086_add_sections"),
    ]

    operations = [
        migrations.RunPython(
            set_section_and_resource_comments,
            reverse_code=reverse_section_and_resource_comments,
        ),
    ]
