# Generated by Django 4.2.22 on 2025-07-10 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0087_move_comments_to_section_and_resource"),
    ]

    operations = [
        migrations.RemoveField(model_name="entity", name="group_comment"),
        migrations.RemoveField(model_name="entity", name="resource_comment"),
    ]
