# Generated by Django 4.2.22 on 2025-07-12 12:13

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0089_remove_entity_group_and_resource_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="new_key",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.RenameField(model_name="entity", old_name="key", new_name="old_key"),
    ]
