# Generated by Django 4.2.22 on 2025-07-12 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0091_set_entity_new_key"),
    ]

    operations = [
        migrations.RenameField(model_name="entity", old_name="new_key", new_name="key"),
        migrations.RemoveField(model_name="entity", name="context"),
        migrations.RemoveField(model_name="entity", name="old_key"),
    ]
