# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0091_add_fulltext_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="locale",
            name="db_collation",
            field=models.CharField(
                blank=True,
                help_text=b"\n        Some of locales require to use different database collation than default ('en_US').\n\n        <strong>Use with caution, because it may brake the search for this locale.</strong>\n        ",
                max_length=20,
            ),
        )
    ]
