# Generated by Django 4.2.22 on 2025-07-13 08:12

from json import dumps, loads

from django.db import migrations


def set_meta_from_source(apps, schema_editor):
    Entity = apps.get_model("base", "Entity")

    entities = Entity.objects.exclude(source=[])
    for entity in entities:
        if isinstance(entity.source, list) and not any(
            m[0] == "reference" for m in entity.meta
        ):
            entity.meta += [["reference", ":".join(ref)] for ref in entity.source]
        elif isinstance(entity.source, dict):
            entity.meta.append(["placeholders", dumps(entity.source)])
    Entity.objects.bulk_update(entities, ["meta"], batch_size=10_000)


def set_source_from_meta(apps, schema_editor):
    Entity = apps.get_model("base", "Entity")

    ref_entities = Entity.objects.filter(meta__contains=["reference"])
    for entity in ref_entities:
        entity.source = [
            ref.split(":") for key, ref in entity.meta if key == "reference"
        ]
    Entity.objects.bulk_update(ref_entities, ["source"], batch_size=10_000)

    ph_entities = Entity.objects.filter(meta__contains=["placeholders"])
    for entity in ph_entities:
        entity.source = loads(
            next(ref for key, ref in entity.meta if key == "placeholders")
        )
    Entity.objects.bulk_update(ph_entities, ["source"], batch_size=10_000)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0093_delete_more_empty_gettext_plurals"),
    ]

    operations = [
        migrations.RunPython(set_meta_from_source, reverse_code=set_source_from_meta),
        migrations.RemoveField(model_name="entity", name="source"),
    ]
