# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 09:17
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import TextField, Value
from django.db.models.functions import Concat


def set_entity_document(apps, schema_editor):
    Entity = apps.get_model('base', 'Entity')
    Entity.objects.update(
        document=Concat('key', Value(' '), 'string', Value(' '), 'string_plural', Value(' '), 'comment')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_auto_20170517_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='document',
            field=TextField(blank=True),
        ),

        migrations.RunPython(set_entity_document, migrations.RunPython.noop)
    ]
