# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_improve_calculate_stats_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailingCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[(b'warning', b'Warning'), (b'error', b'Error')], db_index=True, max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failing_checks', to='base.Translation')),
            ],
        ),
        migrations.AddField(
            model_name='locale',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locale',
            name='warnings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='warnings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectlocale',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectlocale',
            name='warnings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translatedresource',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translatedresource',
            name='warnings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='failingcheck',
            unique_together=set([('severity', 'message', 'translation')]),
        ),
    ]
