# Generated by Django 4.2.22 on 2025-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0095_alter_resource_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="value",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="entity",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
