# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0095_pontoon_intro_permalink_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translation",
            name="rejected_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="rejected_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rejected_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="unrejected_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="unrejected_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unrejected_translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
