# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 21:01
from __future__ import unicode_literals

from bulk_update.helper import bulk_update
from django.db import migrations, models


TRANSLATOR_LOCALES = {
    "af": "af",
    "ar": "ar",
    "bg": "bg",
    "bs": "bs-Latn",
    "ca": "ca",
    "cs": "cs",
    "cy": "cy",
    "da": "da",
    "de": "de",
    "el": "el",
    "en-GB": "en",
    "es": "es",
    "es-AR": "es",
    "es-CL": "es",
    "es-ES": "es",
    "es-MX": "es",
    "et": "et",
    "fa": "fa",
    "fi": "fi",
    "fr": "fr",
    "he": "he",
    "hi-IN": "hi",
    "hr": "hr",
    "ht": "ht",
    "hu": "hu",
    "id": "id",
    "it": "it",
    "ja": "ja",
    "ko": "ko",
    "lt": "lt",
    "lv": "lv",
    "ms": "ms",
    "nl": "nl",
    "no": "nb-NO",
    "pl": "pl",
    "pt": "pt-BR",
    "pt": "pt-PT",
    "ro": "ro",
    "ru": "ru",
    "sk": "sk",
    "sl": "sl",
    "sr-Cyrl": "sr",
    "sv": "sv-SE",
    "sw": "sw",
    "th": "th",
    "tr": "tr",
    "uk": "uk",
    "ur": "ur",
    "vi": "vi",
    "zh-CN": "zh-CHS",
    "zh-HK": "zh-CHT",
    "zh-TW": "zh-CHT",
}


TERMINOLOGY_LOCALES = {
    "af": "af-za",
    "am": "am-et",
    "ar": "ar-sa",
    "as": "as-in",
    "az": "az-latn-az",
    "be": "be-by",
    "bg": "bg-bg",
    "bn": "bn-bd",
    "bn-BD": "bn-bd",
    "bn-IN": "bn-in",
    "bs": "bs-latn-ba",
    "ca": "ca-es",
    "cs": "cs-cz",
    "cy": "cy-gb",
    "da": "da-dk",
    "de": "de-de",
    "el": "el-gr",
    "en": "en-us",
    "en-GB": "en-gb",
    "en-US": "en-us",
    "en-ZA": "en-za",
    "es": "es-es",
    "es-AR": "es-ar",
    "es-CL": "es-cl",
    "es-ES": "es-es",
    "es-MX": "es-mx",
    "et": "et-ee",
    "eu": "eu-es",
    "fa": "fa-ir",
    "fi": "fi-fi",
    "fr": "fr-fr",
    "ga-IE": "ga-ie",
    "gd": "gd-gb",
    "gl": "gl-es",
    "gu-IN": "gu-in",
    "ha": "ha-latn-ng",
    "he": "he-il",
    "hi-IN": "hi-in",
    "hr": "hr-hr",
    "hu": "hu-hu",
    "hy-AM": "hy-am",
    "id": "id-id",
    "ig": "ig-ng",
    "is": "is-is",
    "it": "it-it",
    "ja": "ja-jp",
    "ka": "ka-ge",
    "kk": "kk-kz",
    "km": "km-kh",
    "kn": "kn-in",
    "ko": "ko-kr",
    "ku": "ku-arab-iq",
    "lo": "lo-la",
    "lt": "lt-lt",
    "lv": "lv-lv",
    "mk": "mk-mk",
    "ml": "ml-in",
    "mn": "mn-mn",
    "mr": "mr-in",
    "ms": "ms-my",
    "my": "my-mm",
    "nb-NO": "nb-no",
    "ne-NP": "ne-np",
    "nl": "nl-nl",
    "nn-NO": "nn-no",
    "or": "or-in",
    "pa-IN": "pa-in",
    "pl": "pl-pl",
    "pt-BR": "pt-br",
    "pt-PT": "pt-pt",
    "ro": "ro-ro",
    "ru": "ru-ru",
    "ses": "",
    "si": "si-lk",
    "sk": "sk-sk",
    "sl": "sl-si",
    "son": "",
    "sq": "sq-al",
    "sr": "sr-cyrl-rs",
    "sv-SE": "sv-se",
    "sw": "sw-ke",
    "ta": "ta-in",
    "te": "te-in",
    "tg": "tg-cyrl-tj",
    "th": "th-th",
    "tl": "tl-ph",
    "tr": "tr-tr",
    "uk": "uk-ua",
    "ur": "ur-pk",
    "uz": "uz-latn-uz",
    "vi": "vi-vn",
    "wo": "wo-sn",
    "xh": "xh-za",
    "yo": "yo-ng",
    "zh-CN": "zh-cn",
    "zh-HK": "zh-hk",
    "zh-TW": "zh-tw",
    "zu": "zu-za",
}


def migrate_locales(apps, schema_editor):
    """
    Add alternative locale codes for our integrations with Microsoft products.
    """
    Locale = apps.get_model("base", "Locale")
    locale_map = {l.code: l for l in Locale.objects.all()}

    for pontoon_code, ms_code in filter(lambda x: x[1], TRANSLATOR_LOCALES.items()):
        if pontoon_code in locale_map:
            locale_map[pontoon_code].ms_translator_code = ms_code

    for pontoon_code, ms_code in filter(lambda x: x[1], TERMINOLOGY_LOCALES.items()):
        if pontoon_code in locale_map:
            locale_map[pontoon_code].ms_terminology_code = ms_code

    bulk_update(
        list(locale_map.values()),
        update_fields=["ms_translator_code", "ms_terminology_code"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0097_reject_suggestions_older_than_approved_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="locale",
            name="ms_terminology_code",
            field=models.CharField(
                blank=True,
                help_text="\n        Microsoft Terminology uses language codes that include both the language and\n        the country/region. Chose a matching locale from the list or leave blank to disable support\n        for Microsoft terminology:\n\n        af-za, am-et, ar-dz, ar-eg, ar-sa, as-in, az-latn-az, be-by, bg-bg, bn-bd, bn-in,\n        bs-cyrl-ba, bs-latn-ba, ca-es, ca-es-valencia, chr-cher-us, cs-cz, cy-gb, da-dk, de-at,\n        de-ch, de-de, el-gr, en-au, en-ca, en-gb, en-hk, en-ie, en-in, en-my, en-ng, en-nz, en-ph,\n        en-pk, en-sg, en-tt, en-us, en-za, es-ar, es-bo, es-cl, es-co, es-cr, es-do, es-ec, es-es,\n        es-gt, es-hn, es-mx, es-ni, es-pa, es-pe, es-pr, es-py, es-sv, es-us, es-uy, es-ve, et-ee,\n        eu-es, fa-ir, fi-fi, fil-ph, fo-fo, fr-be, fr-ca, fr-ch, fr-dz, fr-fr, fr-ma, fr-tn,\n        fuc-latn-sn, ga-ie, gd-gb, gl-es, gu-in, guc-ve, ha-latn-ng, he-il, hi-in, hr-hr, hu-hu,\n        hy-am, id-id, ig-ng, is-is, it-ch, it-it, iu-latn-ca, ja-jp, ka-ge, kk-kz, km-kh, kn-in,\n        ko-kr, kok-in, ku-arab-iq, ky-kg, lb-lu, lo-la, lt-lt, lv-lv, mi-nz, mk-mk, ml-in, mn-mn,\n        mr-in, ms-bn, ms-my, mt-mt, my-mm, nb-no, ne-np, nl-be, nl-nl, nn-no, nso-za, or-in,\n        pa-arab-pk, pa-in, pl-pl, prs-af, ps-af, pt-br, pt-pt, quc-latn-gt, quz-pe, ro-md, ro-ro,\n        ru-kz, ru-ru, rw-rw, sd-arab-pk, si-lk, sk-sk, sl-si, sp-xl, sq-al, sr-cyrl-ba, sr-cyrl-rs,\n        sr-latn-me, sr-latn-rs, sv-se, sw-ke, ta-in, te-in, tg-cyrl-tj, th-th, ti-et, tk-tm, tl-ph,\n        tn-za, tr-tr, tt-ru, ug-cn, uk-ua, ur-pk, uz-cyrl-uz, uz-latn-uz, vi-vn, wo-sn, xh-za,\n        yo-ng, zh-cn, zh-hk, zh-sg, zh-tw, zu-za\n        ",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="locale",
            name="ms_translator_code",
            field=models.CharField(
                blank=True,
                help_text='\n        Microsoft Translator maintains its own list of\n        <a href="https://msdn.microsoft.com/en-us/library/hh456380.aspx">supported locales</a>.\n        Choose a locale from that list that\'s is the closest match or leave it blank to disable\n        support for Microsoft Translator.\n        ',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="locale",
            name="plural_rule",
            field=models.CharField(
                blank=True,
                help_text='\n        Plural rule is part of the plurals header in\n        <a href="https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms">\n        Gettext PO files\n        </a>,\n        that follows the <i>plural=</i> string, without the trailing semicolon.\n        E.g. (n != 1)\n        ',
                max_length=128,
            ),
        ),
        migrations.RunPython(migrate_locales, migrations.RunPython.noop,),
    ]
