# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 21:01
from __future__ import unicode_literals

from bulk_update.helper import bulk_update
from django.db import migrations, models


TRANSLATOR_LOCALES = {
    u'af': u'af',
    u'ar': u'ar',
    u'bg': u'bg',
    u'bs': u'bs-Latn',
    u'ca': u'ca',
    u'cs': u'cs',
    u'cy': u'cy',
    u'da': u'da',
    u'de': u'de',
    u'el': u'el',
    u'en-GB': u'en',
    u'es': u'es',
    u'es-AR': u'es',
    u'es-CL': u'es',
    u'es-ES': u'es',
    u'es-MX': u'es',
    u'et': u'et',
    u'fa': u'fa',
    u'fi': u'fi',
    u'fr': u'fr',
    u'he': u'he',
    u'hi-IN': u'hi',
    u'hr': u'hr',
    u'ht': u'ht',
    u'hu': u'hu',
    u'id': u'id',
    u'it': u'it',
    u'ja': u'ja',
    u'ko': u'ko',
    u'lt': u'lt',
    u'lv': u'lv',
    u'ms': u'ms',
    u'nl': u'nl',
    u'no': u'nb-NO',
    u'pl': u'pl',
    u'pt': u'pt-BR',
    u'pt': u'pt-PT',
    u'ro': u'ro',
    u'ru': u'ru',
    u'sk': u'sk',
    u'sl': u'sl',
    u'sr-Cyrl': u'sr',
    u'sv': u'sv-SE',
    u'sw': u'sw',
    u'th': u'th',
    u'tr': u'tr',
    u'uk': u'uk',
    u'ur': u'ur',
    u'vi': u'vi',
    u'zh-CN': u'zh-CHS',
    u'zh-HK': u'zh-CHT',
    u'zh-TW': u'zh-CHT',
}


TERMINOLOGY_LOCALES = {
    u'af': u'af-za',
    u'am': u'am-et',
    u'ar': u'ar-sa',
    u'as': u'as-in',
    u'az': u'az-latn-az',
    u'be': u'be-by',
    u'bg': u'bg-bg',
    u'bn': u'bn-bd',
    u'bn-BD': u'bn-bd',
    u'bn-IN': u'bn-in',
    u'bs': u'bs-latn-ba',
    u'ca': u'ca-es',
    u'cs': u'cs-cz',
    u'cy': u'cy-gb',
    u'da': u'da-dk',
    u'de': u'de-de',
    u'el': u'el-gr',
    u'en': u'en-us',
    u'en-GB': u'en-gb',
    u'en-US': u'en-us',
    u'en-ZA': u'en-za',
    u'es': u'es-es',
    u'es-AR': u'es-ar',
    u'es-CL': u'es-cl',
    u'es-ES': u'es-es',
    u'es-MX': u'es-mx',
    u'et': u'et-ee',
    u'eu': u'eu-es',
    u'fa': u'fa-ir',
    u'fi': u'fi-fi',
    u'fr': u'fr-fr',
    u'ga-IE': u'ga-ie',
    u'gd': u'gd-gb',
    u'gl': u'gl-es',
    u'gu-IN': u'gu-in',
    u'ha': u'ha-latn-ng',
    u'he': u'he-il',
    u'hi-IN': u'hi-in',
    u'hr': u'hr-hr',
    u'hu': u'hu-hu',
    u'hy-AM': u'hy-am',
    u'id': u'id-id',
    u'ig': u'ig-ng',
    u'is': u'is-is',
    u'it': u'it-it',
    u'ja': u'ja-jp',
    u'ka': u'ka-ge',
    u'kk': u'kk-kz',
    u'km': u'km-kh',
    u'kn': u'kn-in',
    u'ko': u'ko-kr',
    u'ku': u'ku-arab-iq',
    u'lo': u'lo-la',
    u'lt': u'lt-lt',
    u'lv': u'lv-lv',
    u'mk': u'mk-mk',
    u'ml': u'ml-in',
    u'mn': u'mn-mn',
    u'mr': u'mr-in',
    u'ms': u'ms-my',
    u'my': u'my-mm',
    u'nb-NO': u'nb-no',
    u'ne-NP': u'ne-np',
    u'nl': u'nl-nl',
    u'nn-NO': u'nn-no',
    u'or': u'or-in',
    u'pa-IN': u'pa-in',
    u'pl': u'pl-pl',
    u'pt-BR': u'pt-br',
    u'pt-PT': u'pt-pt',
    u'ro': u'ro-ro',
    u'ru': u'ru-ru',
    u'ses': u'',
    u'si': u'si-lk',
    u'sk': u'sk-sk',
    u'sl': u'sl-si',
    u'son': u'',
    u'sq': u'sq-al',
    u'sr': u'sr-cyrl-rs',
    u'sv-SE': u'sv-se',
    u'sw': u'sw-ke',
    u'ta': u'ta-in',
    u'te': u'te-in',
    u'tg': u'tg-cyrl-tj',
    u'th': u'th-th',
    u'tl': u'tl-ph',
    u'tr': u'tr-tr',
    u'uk': u'uk-ua',
    u'ur': u'ur-pk',
    u'uz': u'uz-latn-uz',
    u'vi': u'vi-vn',
    u'wo': u'wo-sn',
    u'xh': u'xh-za',
    u'yo': u'yo-ng',
    u'zh-CN': u'zh-cn',
    u'zh-HK': u'zh-hk',
    u'zh-TW': u'zh-tw',
    u'zu': u'zu-za',
}


def migrate_locales(apps, schema_editor):
    """
    Add alternative locale codes for our integrations with Microsoft products.
    """
    Locale = apps.get_model('base', 'Locale')
    locale_map = {l.code: l for l in Locale.objects.all()}

    for pontoon_code, ms_code in filter(lambda x: x[1], TRANSLATOR_LOCALES.items()):
        if pontoon_code in locale_map:
            locale_map[pontoon_code].ms_translator_code = ms_code

    for pontoon_code, ms_code in filter(lambda x: x[1], TERMINOLOGY_LOCALES.items()):
        if pontoon_code in locale_map:
            locale_map[pontoon_code].ms_terminology_code = ms_code

    bulk_update(list(locale_map.values()), update_fields=['ms_translator_code', 'ms_terminology_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_reject_suggestions_older_than_approved_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='ms_terminology_code',
            field=models.CharField(blank=True, help_text='\n        Microsoft Terminology uses language codes that include both the language and\n        the country/region. Chose a matching locale from the list or leave blank to disable support\n        for Microsoft terminology:\n\n        af-za, am-et, ar-dz, ar-eg, ar-sa, as-in, az-latn-az, be-by, bg-bg, bn-bd, bn-in,\n        bs-cyrl-ba, bs-latn-ba, ca-es, ca-es-valencia, chr-cher-us, cs-cz, cy-gb, da-dk, de-at,\n        de-ch, de-de, el-gr, en-au, en-ca, en-gb, en-hk, en-ie, en-in, en-my, en-ng, en-nz, en-ph,\n        en-pk, en-sg, en-tt, en-us, en-za, es-ar, es-bo, es-cl, es-co, es-cr, es-do, es-ec, es-es,\n        es-gt, es-hn, es-mx, es-ni, es-pa, es-pe, es-pr, es-py, es-sv, es-us, es-uy, es-ve, et-ee,\n        eu-es, fa-ir, fi-fi, fil-ph, fo-fo, fr-be, fr-ca, fr-ch, fr-dz, fr-fr, fr-ma, fr-tn,\n        fuc-latn-sn, ga-ie, gd-gb, gl-es, gu-in, guc-ve, ha-latn-ng, he-il, hi-in, hr-hr, hu-hu,\n        hy-am, id-id, ig-ng, is-is, it-ch, it-it, iu-latn-ca, ja-jp, ka-ge, kk-kz, km-kh, kn-in,\n        ko-kr, kok-in, ku-arab-iq, ky-kg, lb-lu, lo-la, lt-lt, lv-lv, mi-nz, mk-mk, ml-in, mn-mn,\n        mr-in, ms-bn, ms-my, mt-mt, my-mm, nb-no, ne-np, nl-be, nl-nl, nn-no, nso-za, or-in,\n        pa-arab-pk, pa-in, pl-pl, prs-af, ps-af, pt-br, pt-pt, quc-latn-gt, quz-pe, ro-md, ro-ro,\n        ru-kz, ru-ru, rw-rw, sd-arab-pk, si-lk, sk-sk, sl-si, sp-xl, sq-al, sr-cyrl-ba, sr-cyrl-rs,\n        sr-latn-me, sr-latn-rs, sv-se, sw-ke, ta-in, te-in, tg-cyrl-tj, th-th, ti-et, tk-tm, tl-ph,\n        tn-za, tr-tr, tt-ru, ug-cn, uk-ua, ur-pk, uz-cyrl-uz, uz-latn-uz, vi-vn, wo-sn, xh-za,\n        yo-ng, zh-cn, zh-hk, zh-sg, zh-tw, zu-za\n        ', max_length=20),
        ),
        migrations.AddField(
            model_name='locale',
            name='ms_translator_code',
            field=models.CharField(blank=True, help_text='\n        Microsoft Translator maintains its own list of\n        <a href="https://msdn.microsoft.com/en-us/library/hh456380.aspx">supported locales</a>.\n        Choose a locale from that list that\'s is the closest match or leave it blank to disable\n        support for Microsoft Translator.\n        ', max_length=20),
        ),
        migrations.AlterField(
            model_name='locale',
            name='plural_rule',
            field=models.CharField(blank=True, help_text='\n        Plural rule is part of the plurals header in\n        <a href="https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms">\n        Gettext PO files\n        </a>,\n        that follows the <i>plural=</i> string, without the trailing semicolon.\n        E.g. (n != 1)\n        ', max_length=128),
        ),
        migrations.RunPython(
            migrate_locales,
            migrations.RunPython.noop,
        )
    ]
