# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0101_userprofile_custom_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="locale",
            name="transvision",
            field=models.BooleanField(
                default=False,
                help_text='\n        Enable Machinery suggestions from <a href="https://transvision.mozfr.org/">Transvision</a>.\n        Only useful for locales that don\'t translate all projects on Pontoon.\n    ',
            ),
        ),
    ]
