# Generated by Django 4.2.26 on 2025-12-02 07:18

from django.db import migrations


def create_pretranslators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="pretranslators")


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0101_webext_as_mf2"),
    ]

    operations = [
        migrations.RunPython(create_pretranslators_group),
    ]
