# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 11:37
from __future__ import unicode_literals

from bulk_update.helper import bulk_update

from django.db import migrations
from django.db.models import F


def rename_groups_with_duplicate_words(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups_to_update = []

    for name in ('managers', 'translators'):
        double = '{} {}'.format(name, name)
        for group in Group.objects.filter(name__contains=double):
            group.name = group.name.replace(double, name)
            groups_to_update.append(group)

    bulk_update(groups_to_update, update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_locale_transvision'),
    ]

    operations = [
        migrations.RunPython(
            rename_groups_with_duplicate_words,
            migrations.RunPython.noop
        ),
    ]
