# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 11:37
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F, Func, Value


def rename_groups_with_duplicate_words(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    for name in ("managers", "translators"):
        double = "{} {}".format(name, name)

        Group.objects.filter(name__contains=double).update(
            name=Func(F("name"), Value(double), Value(name), function="replace",)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0102_locale_transvision"),
    ]

    operations = [
        migrations.RunPython(
            rename_groups_with_duplicate_words, migrations.RunPython.noop
        ),
    ]
