# Generated by Django 4.2.22 on 2025-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0103_xliff_as_mf2"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="value",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="translation",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
