# Generated by Django 4.2.27 on 2026-01-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_xliff_as_mf2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='langpack_url',
        ),
    ]
