# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-19 21:19
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q, F, Func, Value


def unescape_quotes_in_tm_entries_from_android_strings_dtd(apps, schema):
    """
    Handling of different escape sequences for mobile Android strings was fixed in eb5f8d5. However,
    data migration in 4537eac only covered the Translation model, leaving out TranslationMemoryEntry.
    See bugs 1390111 and 1390113 for more details.
    """
    TranslationMemoryEntry = apps.get_model('base', 'TranslationMemoryEntry')

    TranslationMemoryEntries = TranslationMemoryEntry.objects.filter(
        entity__resource__path__contains="mobile/android/base"
    )

    TranslationMemoryEntries.filter(target__contains='\\u0022').update(
        target=Func(
            F('target'),
            Value('\\u0022'), Value('"'),
            function='replace',
        )
    )

    TranslationMemoryEntries.filter(target__contains='\\u0027').update(
        target=Func(
            F('target'),
            Value('\\u0027'), Value("'"),
            function='replace',
        )
    )

    TranslationMemoryEntries.filter(source__contains='\\u0022').update(
        source=Func(
            F('source'),
            Value('\\u0022'), Value('"'),
            function='replace',
        )
    )

    TranslationMemoryEntries.filter(source__contains='\\u0027').update(
        source=Func(
            F('source'),
            Value('\\u0027'), Value("'"),
            function='replace',
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_update_descriptions'),
    ]

    operations = [
        migrations.RunPython(
            unescape_quotes_in_tm_entries_from_android_strings_dtd,
            migrations.RunPython.noop
        )
    ]
