# Generated by Django 4.2.27 on 2026-01-31 16:21

import logging

from django.db import migrations


log = logging.getLogger(__name__)


def create_pm_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    group, created = Group.objects.get_or_create(name="project_managers")
    if not created:
        log.info("'project_managers' group already exists.")
        return

    log.info("Created 'project_managers' group.")

    project_content_type = ContentType.objects.get_or_create(
        app_label="base", model="project"
    )

    permission, _ = Permission.objects.get_or_create(
        codename="can_manage_project",
        content_type=project_content_type,
    )

    group.permissions.add(permission)
    log.info(f"Added 'can_manage_project' permission to {group.name}")


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0105_fix_mf2_translations"),
    ]

    operations = [
        migrations.RunPython(create_pm_group, reverse_code=migrations.RunPython.noop),
    ]
