# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 22:44
from __future__ import unicode_literals

from django.db import migrations


def remove_tm_entries_of_fuzzy_translations(apps, schema):
    """
    Before bug 1415979 was fixed, we created TranslationMemoryDntry objects for all imported
    translations, even if they were fuzzy. Those objects need to be removed.
    """
    TranslationMemoryEntry = apps.get_model('base', 'TranslationMemoryEntry')
    TranslationMemoryEntry.objects.filter(translation__fuzzy=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0105_unescape_quotes_from_android_strings_dtd_in_translation_memory'),
    ]

    operations = [
        migrations.RunPython(
            remove_tm_entries_of_fuzzy_translations,
            migrations.RunPython.noop
        )
    ]
