# Generated by Django 4.2.27 on 2026-01-31 16:21

import logging

from django.db import migrations


log = logging.getLogger(__name__)


def create_pm_group(apps, schema_editor):
    # 1. Get the models we need from the historical state
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # 2. Get or Create the 'project_managers' group
    group, created = Group.objects.get_or_create(name="project_managers")
    if created:
        log.info("Created 'project_managers' group.")
    else:
        log.info("'project_managers' group already exists.")

    # 3. Ensure the 'can_manage_project' permission exists
    project_content_type = ContentType.objects.get(app_label="base", model="project")

    permission = Permission.objects.get(
        codename="can_manage_project",
        content_type=project_content_type,
    )

    # 4. Assign the permission to the group
    group.permissions.add(permission)
    log.info(f"Added 'can_manage_project' permission to {group.name}")


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0105_fix_mf2_translations"),
        ("auth", "0001_initial"),
        ("contenttypes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_pm_group, reverse_code=migrations.RunPython.noop),
    ]
