# Generated by Django 4.2.28 on 2026-03-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0106_create_project_managers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="search_exclude_source_strings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="search_identifiers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="search_match_case",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="search_match_whole_word",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="search_rejected_translations",
            field=models.BooleanField(default=False),
        ),
    ]
