# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_remove_fuzzy_tm_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_source',
            field=models.CharField(choices=[('repository', 'Repository'), ('database', 'Database')], default='repository', max_length=255),
        ),
    ]
