# Generated by Django 4.2.22 on 2025-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("base", "0107_add_search_settings_to_userprofile")]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="value",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="translation",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
