# Generated by Django 4.2.29 on 2026-04-08 02:33

from django.db import migrations


def delete_socialapps(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    SocialApp.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0107_add_search_settings_to_userprofile"),
        ("socialaccount", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(delete_socialapps, migrations.RunPython.noop),
    ]
