# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0108_reverse_accessors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
