# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-20 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0108_reverse_accessors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionChangelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_permissions_log', to=settings.AUTH_USER_MODEL)),
                ('performed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisions_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'User permissions log',
                'verbose_name_plural': 'Users permissions logs',
            },
        ),
    ]
