# Generated by Django 4.2.29 on 2026-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0109_add_translation_value_and_properties_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="value",
            field=models.JSONField(),
        ),
    ]
