# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0111_add_idx_entity_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translatedresource',
            unique_together=set([('locale', 'resource')]),
        ),
    ]
