# Generated by Django 5.2.14 on 2026-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0113_userbanlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="readonly",
            field=models.BooleanField(
                default=False,
                help_text="\n        If true, sync pulls from this repo but never commits or pushes\n        to it. Translations live only in Pontoon's database.\n    ",
                verbose_name="Read-only",
            ),
        ),
    ]
