# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0113_idx_trans_locale_user_entity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('project', 'path')]),
        ),
    ]
