# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0113_idx_trans_locale_user_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locale',
            options={'ordering': ['code'], 'permissions': (('can_translate_locale', 'Can add translations'), ('can_manage_locale', 'Can manage locale'))},
        ),
    ]
