# Generated by Django 5.2.13 on 2026-05-20 09:37

import django.db.models.functions.text

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0114_dedup_userprofile_usernames"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                condition=models.Q(("username__isnull", False)),
                name="base_userprofile_username_lower_uniq",
            ),
        ),
    ]
