# Generated by Django 5.2.13 on 2026-05-29 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0115_alter_userprofile_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locale",
            name="systran_translate_code",
        ),
        migrations.RemoveField(
            model_name="locale",
            name="systran_translate_profile",
        ),
    ]
