# Generated by Django 5.2.13 on 2026-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0116_remove_systran_locale_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="editor_theme",
            field=models.CharField(
                choices=[
                    ("dark", "Dark"),
                    ("light", "Light"),
                    ("match", "Match main"),
                ],
                default="match",
                max_length=20,
            ),
        ),
    ]
