# Generated by Django 5.2.14 on 2026-06-11 19:42

import django.contrib.postgres.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0116_remove_systran_locale_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dashboard_locales",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
