# Generated by Django 5.2.14 on 2026-06-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0117_userprofile_dashboard_locales'),
        ('base', '0117_userprofile_editor_theme'),
    ]

    operations = [
    ]
