# Generated by Django 5.2.14 on 2026-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0118_fix_terminology_entity_value'),
        ('base', '0118_merge_20260624_0350'),
    ]

    operations = [
    ]
