# Generated by Django 5.2.14 on 2026-07-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_repository_readonly'),
        ('base', '0118_fix_terminology_entity_value'),
    ]

    operations = [
    ]
