# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 11:35

from django.db import migrations


# The previous version of this migration has been removed to avoid failures in the future.
# More info: https://github.com/mozilla/pontoon/pull/1119

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_plural_rule_max_length_1639'),
    ]

    operations = []
