# Generated by Django 5.2.14 on 2026-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0120_fix_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="set_locales_from_repo",
            field=models.BooleanField(
                default=False,
                help_text="\n        Control target locales by their directories' presence in the target repository,\n        or in the root locales config if `configuration_file` is not None.\n        ",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="set_translated_resources_from_repo",
            field=models.BooleanField(
                default=False,
                help_text="\n        If `set_locales_from_repo` is True and `configuration_file` is None,\n        setting `set_translated_resources_from_repo` to True will\n        control the availability of each resource for translation in each locale\n        according to the presence of a file (even if empty) at its expected target path.\n\n        If `set_locales_from_repo` is False or `configuration_file` is not None,\n        this control has no effect.\n        ",
            ),
        ),
    ]
