# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0120_bug_1423679_update_plurals_20180417_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sync_disabled',
            field=models.BooleanField(default=False, help_text='\n        Prevent project from syncing with VCS.\n    '),
        ),
        migrations.AlterField(
            model_name='locale',
            name='ms_translator_code',
            field=models.CharField(blank=True, help_text='\n        Microsoft Translator maintains its own list of\n        <a href="https://docs.microsoft.com/en-us/azure/cognitive-services/translator/languages">\n        supported locales</a>. Choose a locale from that list that\'s is the closest match or leave\n        it blank to disable support for Microsoft Translator.\n        ', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='disabled',
            field=models.BooleanField(default=False, help_text='\n        Hide project from the UI and only keep it accessible from the admin.\n        Disable the project instead of deleting it to keep translation memory\n        and attributions. Also prevents project from syncing with VCS.\n    '),
        ),
    ]
