# Generated by Django 5.2.15 on 2026-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0120_fix_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="monthly_health_report",
            field=models.BooleanField(default=False),
        ),
    ]
