# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0121_bug_1453999_disable_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.CharField(blank=True, choices=[('dtd', 'dtd'), ('ftl', 'ftl'), ('inc', 'inc'), ('ini', 'ini'), ('json', 'json'), ('lang', 'lang'), ('po', 'po'), ('properties', 'properties'), ('xlf', 'xliff'), ('xliff', 'xliff')], max_length=20, verbose_name='Format'),
        ),
    ]
