# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0123_rename_translated_to_unreviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='date_obsoleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
