# Generated by Django 5.2.15 on 2026-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0123_mark_system_users_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="monthly_health_report",
            field=models.BooleanField(default=False),
        ),
    ]
