# Generated by Django 5.2.15 on 2026-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0123_mark_system_users_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_chs_project",
            field=models.BooleanField(
                default=False,
                help_text="Used to flag key projects referenced in the Insights Dashboard.",
            ),
        ),
    ]
