# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_entity_date_obsoleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
