# Generated by Django 5.2.15 on 2026-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0124_project_is_chs_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="monthly_health_report",
            field=models.BooleanField(default=False),
        ),
    ]
