# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0125_projectlocale_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tour_status',
            field=models.IntegerField(default=0),
        ),
    ]
