# Generated by Django 5.2.15 on 2026-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0126_set_system_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="monthly_health_report",
            field=models.BooleanField(default=False),
        ),
    ]
