# Generated by Django 5.2.15 on 2026-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0127_add_missing_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="monthly_health_report",
            field=models.BooleanField(default=False),
        ),
    ]
