# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 15:43
from __future__ import unicode_literals

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0128_pontoon-intro_to_system_project'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='translation',
            index=partial_index.PartialIndex(fields=['entity', 'locale', 'plural_form', 'approved'], name='base_transl_entity__1afba0_partial', unique=True, where=partial_index.PQ(approved=True)),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=partial_index.PartialIndex(fields=['entity', 'locale', 'approved'], name='base_transl_entity__42c2b6_partial', unique=True, where=partial_index.PQ((b'plural_form__isnull', True), (b'approved', True))),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=partial_index.PartialIndex(fields=['entity', 'locale', 'plural_form', 'fuzzy'], name='base_transl_entity__feeaaa_partial', unique=True, where=partial_index.PQ(fuzzy=True)),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=partial_index.PartialIndex(fields=['entity', 'locale', 'fuzzy'], name='base_transl_entity__fa59ff_partial', unique=True, where=partial_index.PQ((b'plural_form__isnull', True), (b'fuzzy', True))),
        ),
    ]
