# Generated by Django 5.2.15 on 2026-08-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0129_rename_gpt_transform_machinery_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="monthly_health_report",
            field=models.BooleanField(default=False),
        ),
    ]
