# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:36
from __future__ import unicode_literals

import datetime

from django.db import migrations


def set_active_translations(apps, schema_editor):
    Translation = apps.get_model('base', 'Translation')
    print(datetime.datetime.now().time())

    # All approved translations are active.
    Translation.objects.filter(approved=True).update(active=True)
    print(datetime.datetime.now().time())

    # All fuzzy translations are active.
    # Note that this wasn't the case until this patch - if a fuzzy translation
    # had a newer sibling suggestion, that suggestion was active.
    # However, this is a bug, and we're fixing it here.
    Translation.objects.filter(fuzzy=True).update(active=True)
    print(datetime.datetime.now().time())

    # The most recent unreviewed suggestion for any given combination of
    # (locale, entity, plural_form) is active, unless it has approved or fuzzy
    # siblings.
    # Note that currenty this logic applies to all suggestions, even rejected.
    # However, this is a bug, and we're fixing it here.
    unreviewed_pks = set()
    candidates = Translation.objects.filter(
        approved=False,
        fuzzy=False,
        rejected=False,
    ).values_list('entity', 'locale', 'plural_form')

    for entity, locale, plural_form in candidates:
        siblings = (
            Translation.objects.filter(
                entity=entity,
                locale=locale,
                plural_form=plural_form,
            )
            .exclude(rejected=True)
            .order_by('-active', '-date')
        )
        if siblings and not siblings[0].active:
            unreviewed_pks.add(siblings[0].pk)
    print(datetime.datetime.now().time())

    Translation.objects.filter(pk__in=unreviewed_pks).update(active=True)
    print(datetime.datetime.now().time())


def drop_active_translations(apps, schema_editor):
    Translation = apps.get_model('base', 'Translation')
    Translation.objects.filter(active=True).update(active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0130_translation_active_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(
            set_active_translations,
            drop_active_translations,
        ),
    ]
