# Generated by Django 5.2.15 on 2026-08-21 08:16

from django.db import migrations, models

import pontoon.base.models.locale


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0130_normalize_locale_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locale",
            name="script",
            field=models.CharField(
                blank=True,
                choices=pontoon.base.models.locale.get_script_choices,
                default="Latn",
                help_text='\n        The <a href="https://www.unicode.org/iso15924/iso15924-codes.html">ISO 15924</a>\n        script code used by this locale. Look up the script of a language in\n        <a\n        href="http://www.unicode.org/cldr/charts/latest/supplemental/languages_and_scripts.html">\n        CLDR Languages and Scripts</a>.\n        ',
                max_length=4,
            ),
        ),
    ]
