# Generated by Django 5.2.15 on 2026-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0133_alter_locale_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locale",
            name="google_translate_code",
            field=models.CharField(
                blank=True,
                help_text='\n        Google Cloud Translation maintains its own list of\n        <a href="https://docs.cloud.google.com/translate/docs/languages">\n        supported languages</a>. Choose a matching locale from the list or leave blank to disable\n        support for Google Cloud Translation machine translation service.\n        ',
                max_length=20,
            ),
        ),
    ]
