# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0140_project_resource_date_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locale',
            options={'permissions': (('can_translate_locale', 'Can add translations'), ('can_manage_locale', 'Can manage locale'))},
        ),
    ]
