# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0140_project_resource_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_translate_next',
            field=models.BooleanField(default=False),
        ),
    ]
