# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0141_userprofile_use_translate_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pre_translation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
