# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-01 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0143_migrate_tm_ftl_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='use_translate_next',
        ),
    ]
