# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0146_pretranslate_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='group_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='resource_comment',
            field=models.TextField(blank=True),
        ),
    ]
