# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0148_auto_20191107_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="word_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
