# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

"""
This migration was triggered by black formatting. It doesn't actually change anything
to our models, only text that was formatted differently. Please ignore this as it is
merely cosmetic (and the easiest way to get rid of those false migrations).
"""


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0149_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="changed_locales",
            field=models.ManyToManyField(
                help_text="List of locales in which translations for this entity have changed since the last sync.",
                through="base.ChangedEntityLocale",
                to="base.Locale",
            ),
        ),
        migrations.AlterField(
            model_name="externalresource",
            name="url",
            field=models.URLField(blank=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="locale",
            name="db_collation",
            field=models.CharField(
                blank=True,
                help_text="\n        Some of locales require to use different database collation than default ('en_US').\n\n        <strong>Use with caution, because it may brake the search for this locale.</strong>\n        ",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="\n        Notes only visible in Administration\n    ",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="can_be_requested",
            field=models.BooleanField(
                default=True,
                help_text="\n        Allow localizers to request the project for their team.\n    ",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="\n        L10n driver in charge of the project\n    ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="info",
            field=models.TextField(blank=True, verbose_name="Project info"),
        ),
        migrations.AlterField(
            model_name="project",
            name="langpack_url",
            field=models.URLField(
                blank=True,
                help_text="\n        URL pattern for downloading language packs. Leave empty if language packs\n        not available for the project. Supports {locale_code} wildcard.\n    ",
                null=True,
                verbose_name="Language pack URL",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="links",
            field=models.BooleanField(
                default=False,
                verbose_name="Keep links on the project website clickable",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Lowest"),
                    (2, "Low"),
                    (3, "Normal"),
                    (4, "High"),
                    (5, "Highest"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="project",
            name="width",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="\n        Default website (iframe) width in pixels.\n        If set, sidebar will be opened by default.\n    ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="branch",
            field=models.CharField(blank=True, max_length=2000, verbose_name="Branch"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="permalink_prefix",
            field=models.CharField(
                help_text="\n        A URL prefix for downloading localized files. For GitHub repositories,\n        select any localized file on GitHub, click Raw and replace locale code\n        and the following bits in the URL with `{locale_code}`.\n    ",
                max_length=2000,
                verbose_name="Download prefix",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="source_repo",
            field=models.BooleanField(
                default=False,
                help_text='\n        If true, this repo contains the source strings directly in the\n        root of the repo. Checkouts of this repo will have "templates"\n        appended to the end of their path so that they are detected as\n        source directories.\n    ',
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="type",
            field=models.CharField(
                choices=[("git", "Git"), ("hg", "HG"), ("svn", "SVN")],
                default="git",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="url",
            field=models.CharField(max_length=2000, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="website",
            field=models.URLField(
                blank=True, max_length=2000, verbose_name="Public Repository Website"
            ),
        ),
        migrations.AlterField(
            model_name="subpage",
            name="url",
            field=models.URLField(blank=True, verbose_name="URL"),
        ),
    ]
