# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0149_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.Translation'),
        ),
    ]
