# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0150_auto_20200206_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="permalink_prefix",
            field=models.CharField(
                blank=True,
                help_text="\n        A URL prefix for downloading localized files. For GitHub repositories,\n        select any localized file on GitHub, click Raw and replace locale code\n        and the following bits in the URL with `{locale_code}`.\n    ",
                max_length=2000,
                verbose_name="Download prefix",
            ),
        ),
    ]
