# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0151_permalink_prefix_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="word_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
