# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0151_permalink_prefix_optional"),
        ("base", "0149_add_entity_word_count"),
    ]

    operations = []
