# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 14:04
from __future__ import unicode_literals

from bulk_update.helper import bulk_update

from django.db import migrations

from pontoon.base.models import get_word_count


def add_word_count(apps, schema_editor):
    Entity = apps.get_model("base", "Entity")
    entities = []

    for e in Entity.objects.all():
        e.word_count = get_word_count(e.string)
        entities.append(e)

    bulk_update(entities, update_fields=["word_count"], batch_size=1000)


def reset_word_count(apps, schema_editor):
    Entity = apps.get_model("base", "Entity")
    Entity.objects.all().update(word_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0152_entity_word_count"),
    ]

    operations = [
        migrations.RunPython(add_word_count, reset_word_count,),
    ]
