# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0153_populate_word_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="base.Entity",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="locale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="base.Locale",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="base.Translation",
            ),
        ),
    ]
