# Generated by Django 4.2.11 on 2024-07-24 18:49

from django.db import migrations


def update_locale_code(apps, schema_editor):
    UXActionLog = apps.get_model("uxactionlog", "UXActionLog")

    for log in UXActionLog.objects.filter(action_type="LLM Dropdown Select"):
        data = log.data
        if "targetLanguage" in data:
            data["localeCode"] = data.pop("targetLanguage")
            log.data = data
            log.save()


class Migration(migrations.Migration):
    dependencies = [
        ("uxactionlog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=update_locale_code,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
