name: Frontend

on:
  push:
    branches:
      - main
    paths:
      - translate/**
      - .github/workflows/frontend.yml
  pull_request:
    branches:
      - main
    paths:
      - translate/**
      - .github/workflows/frontend.yml
  workflow_dispatch:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with: { node-version: '22' }
      - name: Install dependencies
        run: npm ci
      - name: Check TypeScript
        run: npm run types -- --pretty
        working-directory: translate
      - name: build
        run: npm run build
        working-directory: translate

  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with: { node-version: '22' }
      - name: Install globals
        run: npm install --global license-checker-rseidelsohn@4.4.2
      - name: Install dependencies
        run: npm ci
      - name: Check licenses
        run: |
          # --failOn doesn't print the licenses on failure.
          # Use jq to print only minimal info, then print a summary when
          # checking for GPL packages.
          license-checker-rseidelsohn --json | jq -r 'to_entries[] | "\(.key): \(.value.licenses)"'
          license-checker-rseidelsohn --summary --failOn 'GPL'

  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
          with:
            persist-credentials: false
        - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
          with: { node-version: '22' }
        - name: Install dependencies
          run: npm ci
        - name: vitest
          run: npm test -- --coverage
          working-directory: translate
        - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
          with:
            flags: frontend
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
