name: Heroku

on:
  push:
    branches:
      - main
    paths:
      - app.json
      - .github/workflows/heroku.yml
  pull_request:
    branches:
      - main
    paths:
      - app.json
      - .github/workflows/heroku.yml
  workflow_dispatch:

jobs:
  app-json:
    name: Validating app.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - name: Validate
        run: python3 -m json.tool < app.json > /dev/null
