name: Validate heroku app.json

on:
  push:
    branches:
      - master
    paths:
      - app.json
      - .github/workflows/heroku.yml
  pull_request:
    branches:
      - master
    paths:
      - app.json
      - .github/workflows/heroku.yml

jobs:
  app-json:
    name: Validate heroku app.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        run: python3 -m json.tool < app.json > /dev/null
