name: Heroku

on:
  push:
    branches:
      - main
    paths:
      - app.json
      - .github/workflows/heroku.yml
  pull_request:
    branches:
      - main
    paths:
      - app.json
      - .github/workflows/heroku.yml
  workflow_dispatch:

jobs:
  app-json:
    name: Validating app.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Validate
        run: python3 -m json.tool < app.json > /dev/null
