name: JavaScript and Jinja linting

on:
  push:
    branches:
      - main
    paths:
      - '**.jinja'
      - '**.js'
      - '**.html'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - package.json
      - '.*eslint*'
      - '.*prettier*'
      - .github/workflows/js-lint.yml
  pull_request:
    branches:
      - main
    paths:
      - '**.jinja'
      - '**.js'
      - '**.html'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - package.json
      - '.*eslint*'
      - '.*prettier*'
      - .github/workflows/js-lint.yml
  workflow_dispatch:

permissions: {}

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: '24' }
      - run: npm ci
      - run: npm run lint

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: '24' }
      - run: npm ci
      - run: npm run check-prettier
