name: JavaScript and Jinja linting

on:
  push:
    branches:
      - main
    paths:
      - '**.jinja'
      - '**.js'
      - '**.html'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - package.json
      - '.*eslint*'
      - '.*prettier*'
      - .github/workflows/js-lint.yml
  pull_request:
    branches:
      - main
    paths:
      - '**.jinja'
      - '**.js'
      - '**.html'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - package.json
      - '.*eslint*'
      - '.*prettier*'
      - .github/workflows/js-lint.yml
  workflow_dispatch:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: npm ci
      - run: npm run lint

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: npm ci
      - run: npm run check-prettier
