name: Python linting

on:
  push:
    branches:
      - main
    paths:
      - pontoon/**.py
      - .github/workflows/py-lint.yml
      - requirements/lint.txt
  pull_request:
    branches:
      - main
    paths:
      - pontoon/**.py
      - .github/workflows/py-lint.yml
      - requirements/lint.txt
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/requirements/*.txt
          # Version should match the one used in docker/Dockerfile*
          version: "0.10.7"
      - name: Install Dependencies
        run: uv pip install -r requirements/lint.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: ruff lint
        run: ruff check
      - name: ruff format
        run: ruff format --check
