name: Non-frontend JavaScript

on:
  push:
    branches:
      - master
    paths:
      - tag-admin/**
      - package.json
      - .github/workflows/tag-admin.yml
  pull_request:
    branches:
      - master
    paths:
      - tag-admin/**
      - package.json
      - .github/workflows/tag-admin.yml
  workflow_dispatch:

jobs:
  test:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install globals
        run: npm install --global codecov npm@8
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
        working-directory: tag-admin
      - name: codecov.io
        run: codecov -F non-frontend-js
      - name: Build
        run: npm run build
