name: Non-frontend JavaScript

on:
  push:
    branches:
      - main
    paths:
      - tag-admin/**
      - package.json
      - .github/workflows/tag-admin.yml
  pull_request:
    branches:
      - main
    paths:
      - tag-admin/**
      - package.json
      - .github/workflows/tag-admin.yml
  workflow_dispatch:

jobs:
  test:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - name: Install globals
        run: npm install --global npm@8
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
        working-directory: tag-admin
      - uses: codecov/codecov-action@v4
        with: { flags: non-frontend-js }
      - name: Build
        run: npm run build
