name: Run Tests
on:
  # Trigger on push to master
  push:
    branches:
      - master
  # Trigger the workflow on pull request events
  # but only for the master branch
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: asdf
      DATABASE_URL: postgres://postgres:postgres@localhost/pontoon
      HMAC_KEY: asdf
      HGPYTHON3: 1

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Test PostgreSQL connection
        run: |
          psql -d postgres://postgres:postgres@localhost/postgres -c "SELECT * FROM pg_collation"
          exit 1

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Linux packages
        # libxslt and libxml2 are needed to compile lxml
        run: |
          sudo apt update -y
          sudo apt install -y libxslt-dev libxml2-dev language-pack-tr

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Node dependencies
        run: |
          node --version
          npm install .
          pushd frontend && npm install && popd

      - name: Install Python dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements/test.txt

      - name: Run linters
        run: |
          black pontoon/ --check
          flake8 pontoon/
          ./node_modules/.bin/prettier --check '**/frontend/**/*.{js,css}' '**/pontoon/**/*.{js,css}' '**/tests/**/*.{js,css}'
          ./node_modules/.bin/eslint .

      - name: Build and collect static assets
        run: |
          ./node_modules/.bin/webpack
          pushd frontend && npm run build && popd
          python manage.py collectstatic -v0 --noinput

      - name: Run tests
        run: |
          py.test --cov-append --cov-report=term --cov=. -v --create-db --migrations
          npm test

      - name: Run all front-end checks
        run: |
          pushd frontend
          npm run flow
          npm test
          popd

      - name: Run code coverage
        run: codecov

      - name: Check validity of Heroku deployment file
        run: cat app.json | python -m json.tool > /dev/null
